### ISSUE TITLE
[REQUEST] Make OctoPi Top Bar ALWAYS visible

### ISSUE THREAD

**Issue by bolsoncerrado** [foosel/OctoPrint#1130]
So we can have the temps bar always visible no matter where we are (in the control tab for example if we are scrolling down past the webcam image, pending the temp hotend being reached so we can extrude, we need to constantly scroll up and down to check if the temp was reached)

**Comment by foosel** [comment]
That used to be done this way, but it causes rendering issues on mobile devices (login dialog doesn't stay open anymore when focusing, so it's impossible to login due to an issue with the bootstrap version, and no, switching to a new one is not just a drop-in-replacement) and hence was removed in commit 02212bde21507d2fbcc5a15e33ecefc850ee0ed5 / version 1.2.0 (see also #257)
