### ISSUE TITLE
Update does not update

### ISSUE THREAD

**Issue by mikecarr** [foosel/OctoPrint#1163]
#### What were you doing?

Either software update in settings or from the notification, I select update, it says "Update Successful" but still on older version.

#### What did you expect to happen?
I expected the software to update and restart the server

#### What happened instead?
Nothing, it says it was successful but it did not update.

#### Branch & Commit or Version of OctoPrint

Version: 1.2.7 (master branch)

#### Printer model & used firmware incl. version

XYZ Da Vinci, Repetiere SW

#### Browser and Version of Browser, Operating System running Browser

Mac OS X 10.11.2
Chrome Version 47.0.2526.106 (64-bit)

#### Link to octoprint.log
 
https://gist.github.com/mikecarr/5e9c2fa536fcf9a5f58c

#### Link to contents of terminal tab or serial.log

na
#### Link to contents of Javascript console in the browser

na
#### Screenshot(s) showing the problem:

na

I have read the FAQ.

**Comment by foosel** [comment]
> I have read the FAQ

Sure? Because [that's in there](https://github.com/foosel/OctoPrint/wiki/FAQ#im-running-127-i-tried-to-update-to-a-newer-version-via-the-software-update-plugin-but-im-still-on-127-after-restart). Also there is the [release notes](https://github.com/foosel/OctoPrint/releases/tag/1.2.8) or the [G+ release announcement](https://plus.google.com/u/0/b/110130855001142142895/+OctoprintOrg/posts/VAttLfxezFN) and even [an existing and open ticket](https://github.com/foosel/OctoPrint/issues/1135), all of them explain why that is and how to solve it.
