### ISSUE TITLE
[Request] Stream to youtube

### ISSUE THREAD

**Issue by boelle** [foosel/OctoPrint#1260]
Hi

I want to record some of my prints with youtube,

I know its possible here: https://support.google.com/youtube/answer/2474026?hl=en

basicly i should just stream to rtmp://a.rtmp.youtube.com/live2 

and it will show up automatic, of course a stream key is needed also but that one i will not show here

**Comment by Naesstrom** [comment]
I second this, was just checking the issues to see if there was a suggestion about it already! :+1:

**Comment by foosel** [comment]
Since OctoPrint is only a consumer of the webcam itself, it doesn't make sense building this into OctoPrint (even as a plugin). Why add on to the load of tasks the tool responsible for keeping your printer fed for something that could be more easily (and better) done with an external tool? I'd suggest looking into vlc or streamer, feed in the mjpg url of the webcam server and have it dump that to YouTube, that's what tools like that are for. OctoPrint is a print server, not a OS ;)
