### ISSUE TITLE
[Request] Plugin for Timelapses

### ISSUE THREAD

**Issue by DylanB00** [foosel/OctoPrint#1334]
Configurations for Timelapses! Imagine being able to modify how your timelapse goes. With a plugin like this, some ideas of features could be to set the specific duration of the timelapse, intervals of taking each image, and more that are all including on a tab of the OctoPrint webpage.

**Comment by markwal** [comment]
There is already Timelapse configuration in OctoPrint that includes interval for each image and a tab on the OctoPrint webpage.  The duration is also settable via frames per seconds and the number of frames is a result of the interval for each image.

There is already a request on the issue tracker for more extensibility in the timelapse system so that plugins can exert more control over, for example, timelapse snapshot triggers.  Is there something else you are requesting here or are you requesting that someone write a timelapse plugin.  And if the latter, what specifically do you want it to do?
