### ISSUE TITLE
[REQUEST] Display Z height on web interface

### ISSUE THREAD

**Issue by CharlieJordan** [foosel/OctoPrint#1355]
I often need to watch the last few layers of a print in order to ensure that I do in fact have everything dialed in ( extrusion multiplier, # of top layers, etc..).

  "Print Time Left" never seems to finish calculating for me, and while the "Printed:" ratio is a useful, though rather coarse" measurement, what would really be useful to me is the Z height. 

  I almost always know the total height and layer height for any object that I'm printing, so if I just knew the current Z height of a print I could easily figure out when to scurry over to the printer to watch the last n layers of a print.

**Comment by foosel** [comment]
There's a plugin for displaying the current z height (according to streamed gcode): http://plugins.octoprint.org/plugins/displayz/

The total height requires a full analysis of the gcode, which doesn't necessarily have taken place yet when starting a print (and can't be done) or isn't even possible (when printing from SD). So that is currently not available, but I'll happily accept PRs on that to add the total calculated height.

Anyhow, already mostly implemented, in the plugin linked above :)
