### ISSUE TITLE
$root.users.confirmUserSettingsDialog is not a function when editing access control options for a user

### ISSUE THREAD

**Issue by javawizard** [foosel/OctoPrint#1357]
#### What were you doing?

Trying to make a non-admin user an admin. Go to Settings -> Access Control, click the edit button next to a user, then click Confirm. Happens whether or not you actually change either of the checkboxes.

#### What did you expect to happen?

Access control settings for the user to update, dialog to go away.

#### What happened instead?

Dialog stays, nothing changes, and I get `VM877:3 Uncaught TypeError: $root.users.confirmUserSettingsDialog is not a function` on the javascript console

#### Branch & Commit or Version of OctoPrint

1.2.11 & 1.2.10

#### Printer model & used firmware incl. version

SeeMeCNC Orion Delta

#### Browser and Version of Browser, Operating System running Browser

Chrome 50.0.2661.102 on Mac OS X 10.10.5 Yosemite

#### Link to octoprint.log

Working on it, though probably not relevant.

#### Link to contents of Javascript console in the browser

Minified, so probably less than helpful, but here's the stack trace anyway.

Uncaught TypeError: $root.users.confirmUserSettingsDialog is not a function
(anonymous function) @ VM877:3
(anonymous function) @ packed_libs.js?35d69079:1020
x.event.dispatch @ packed_libs.js?35d69079:4
y.handle @ packed_libs.js?35d69079:4

I have read the FAQ.

**Comment by foosel** [comment]
Thanks for spotting this (and the full bug report that made it extremely easy to fix this one). Has been solved in `maintenance` and `devel` branch and will be part of the next release.

In the meantime, anyone who runs into this can solve the problem for now by editing `~/.octoprint/users.yaml` and adding `admin` to the roles of a user and then restarting the server, e.g. turning

``` yaml
test:
  roles:
  - user
```

into 

``` yaml
test:
  roles:
  - user
  - admin
```

in order to give admin rights to the user `test`. Only a workaround until the fix is released, but should solve any issues for now hopefully.
