### ISSUE TITLE
Print failing when resend is requested

### ISSUE THREAD

**Issue by jgoldshlag** [foosel/OctoPrint#166]
I just updated to the latest master code, and my prints are now failing as soon as my printer (Prusa i3 with Marlin) requests a resend. It looks like maybe https://github.com/foosel/OctoPrint/commit/bbad030a9227db6ca2df42d393c38fb4db6817a4 is the reason for the failure. I will try rolling back those changes and see if that fixes anything.

My terminal log: (I missed the first error, but this keeps repeating forever)

Recv: ok
Send: N4976G1 X108.029 Y99.790 E9.34505*76
Recv: Error:No Line Number with checksum, Last Line: 4974
Recv: Error:Line Number is not Last Line Number+1, Last Line: 4974
Recv: Resend: 4975
Send: N4975G1 X107.734 Y100.022 E9.33912*121
Recv: ok
Send: N4976G1 X108.029 Y99.790 E9.34505*76
Recv: Error:No Line Number with checksum, Last Line: 4974
Recv: Error:Line Number is not Last Line Number+1, Last Line: 4974
Recv: Resend: 4975
Send: N4975G1 X107.734 Y100.022 E9.33912*121
Recv: ok
Send: N4976G1 X108.029 Y99.790 E9.34505*76
Recv: Error:No Line Number with checksum, Last Line: 4974
Recv: Error:Line Number is not Last Line Number+1, Last Line: 4974
Recv: Resend: 4975
Send: N4975G1 X107.734 Y100.022 E9.33912*121
Recv: ok
Send: N4976G1 X108.029 Y99.790 E9.34505*76
Recv: Error:No Line Number with checksum, Last Line: 4974
Recv: Error:Line Number is not Last Line Number+1, Last Line: 4974
Recv: Resend: 4975
Send: N4975G1 X107.734 Y100.022 E9.33912*121
Recv: ok
Send: N4976G1 X108.029 Y99.790 E9.34505*76
Recv: Error:Line Number is not Last Line Number+1, Last Line: 4974
Recv: Resend: 4975
Send: N4975G1 X107.734 Y100.022 E9.33912*121
Recv: ok
Send: N4976G1 X108.029 Y99.790 E9.34505*76
Recv: Error:Line Number is not Last Line Number+1, Last Line: 4974
Recv: Resend: 4975
Send: N4975G1 X107.734 Y100.022 E9.33912*121
Recv: ok
Send: N4976G1 X108.029 Y99.790 E9.34505*76
Recv: Error:Line Number is not Last Line Number+1, Last Line: 4974
Recv: Resend: 4975
Send: N4975G1 X107.734 Y100.022 E9.33912*121
Recv: ok
Send: N4976G1 X108.029 Y99.790 E9.34505*76
Recv: Error:Line Number is not Last Line Number+1, Last Line: 4974
Recv: Resend: 4975
Send: N4975G1 X107.734 Y100.022 E9.33912*121
Recv: ok
Send: N4976G1 X108.029 Y99.790 E9.34505*76
Recv: Error:No Line Number with checksum, Last Line: 4974
Recv: Error:Line Number is not Last Line Number+1, Last Line: 4974
Recv: Resend: 4975
Send: N4975G1 X107.734 Y100.022 E9.33912*121
Recv: ok
Send: N4976G1 X108.029 Y99.790 E9.34505*76
Recv: Error:Line Number is not Last Line Number+1, Last Line: 4974
Recv: Resend: 4975
Send: N4975G1 X107.734 Y100.022 E9.33912*121
Recv: ok

**Comment by treloid** [comment]
So i was fighting against the samw error like you guys.
Now i fixed it by flashing an older version of the marlin firmware on my printer.
Seems to work now, did 6 prints in a row and not a single error was detected :)

**Comment by foosel** [comment]
As indicated by the commit message above, I introduced ping pong sending ("command" - "ok" - "command" - "ok") into ``devel`` to help mitigate this and other issues. This is *not* the perfect solution to the problem (which is what is being worked on in ``commRefactoring``), but it should help until that becomes ready for prime time. Could people still affected by these problems please give current ``devel`` a try and report back?

**Comment by Thidsa** [comment]
I had this alot several months ago. Loaded a different firmware on my Printrbot and it never happened again, and ive printed alot since then. Been using devel all the time, often updated. So at the time of firmware change(maybe august last year) it still worked right away after the firmware change.  Maybe its not Octoprint's fault
Wanted to tell you

**Comment by syky27** [comment]
Hi! I did not read all the stuff above, but I would like to report that we experience same issue on all 15 printers on FIT CTU. All of the printers uses latest Marlin FW.

**Comment by foosel** [comment]
If you had read all the stuff above, you would know that I pushed a commit
a while back to the devel branch that I hope mitigates the issue. So
without you also reporting the version of OctoPrint you are using, that
comment is sadly not helpful at all.

**Comment by foosel** [comment]
Considering this closed for now due to the quite extreme refactoring that took place in the commit mentioned above which switched to a ping-pong based approach of communication (which while not optimal should have solved the problem) and due to the fact that I did not get any feedback telling me that this is nevertheless still happening with current `devel`. 

New terminal tab offers to fake acknowledgements in case they get lost, new polling for temperature and sd printing status no longer flood the printer during long running commands (which also no longer trigger a timeout and are also configurable through the settings), and a lot of other improvements have been backported from `commRefactoring` too.

**Comment by lobermann** [comment]
Hi. I just ran into this exact issue. Using latest Marlin from 3 days ago (32cec5c3cc15645d4c853aeb0bdb8ff32c39be81)  and Octoprint (Octopi) Version 1.1.1-30-g4fede5a. I pasted the log here http://pastebin.com/pd39CZrk . You can also see my fork that I use here https://github.com/lobermann/Marlin/tree/PrusaI3Hephestos_update .

I am now going ahead and restart that print and see if it fails again or continues. If I encounter it again I will put octoprint in debug and see what I can get. 

If I can test anything else please let me know.

**Comment by foosel** [comment]
Please update. 1.2.0 was released last week, which includes all the changes mentioned above.

**Comment by lobermann** [comment]
ok thanks! will do that. Will post it here if I encounter any more issues.

**Comment by krang00** [comment]
I just started having the same problems. Was running Octopi 1.2.0 RC3 (I believe) and everything was working great. Just upgraded to 1.2.1 and upon my first print I received the "Print failing when resend" error. Restarted the Printrbot and Pi2, printed and it ran great for about 1 hour then just locked up/stopped. I couldn't even get to the Pi2 web server for octoprint. Printing now using Cura and it's been ok.

**Comment by foosel** [comment]
@krang00 Full serial log please, diagnosis if this is even an actual issue is otherwise impossible - those error messages from the firmware can in fact also be just a normal cause of a serial transmission error. And the fact that you couldn't even reach the web server anymore sounds in fact more like a full crash, and I've had people report in the past that they solved both that and their communication issues by getting a proper power supply for the pi, which can be quite finicky when it comes to power. Doesn't mean that's the reason here, but since you experiences both a communication error and what sounds like a crash I'd actually rule that out as a possible cause if it was my setup.

**Comment by krang00** [comment]
Well, so far I've been able to run two full long prints with no issues and Serial debugging on. I'm attributing that one failed print to a Pi2 or other issue. I'll let you know if it happens again and get logs. thanks for your awesome work on this!

**Comment by armator** [comment]
Hello, I had the same issue at the first print. I have latest marlin on prusa i3 clone, and latest octoprint on an odroid-w (a raspberry pi clone).  I have a lousy cable connection to ramps D0/D1 pins to rpi rx-tx pins, with a level converter in between. So a lot of things, especially bad grounding and voltage spikes may have caused this I think... I'm sorry I've lost the error log and cannot paste here.


Then, I've checked "Send a checksum with every command Repetier" and added "G0, G1," to "long commands" settings in the serial configuration settings tab. I had a large (about 20 cm) part to print. I think the problem is over now.

I'll renew the connection cables as soon as I can.

By the way, thank you @foosel, It's a very nice and neat software.

**Comment by foosel** [comment]
Again, seeing a resend request in the log is nothing unusual, only if the request loops and purely electrical reasons and firmware bugs can be ruled out as a cause for that does it make sense to look further.

I also advise against adding G0 and G1 to long running command - by their very definition they are not (the firmware acknowledges them when they enter the movement planner, not when they are actually executed), and since they make up most of the communication during a print having then toggle the "long running flag" constantly will probably only negatively impact performance and do nothing else.

**Comment by armator** [comment]
Yes, I think you are right. I've removed G0, G1 from long running command, and its the same, there is no problem now. Thanks.

**Comment by PulgaFeroz** [comment]
Here's my 2 cents (and an evening of troubleshooting)

My octoprint is setup in a raspberry pi model 1 B (yes one of the first ones with all it's hw quirks) with a solidoodle 2 (pre may 2013, sanguinolu)
It worked fine for a while, only noticeable thing was that the 'connect' doesn't always work as i send a G28 right after connect and some OK is sometimes missing, usually the 1st connect failed
Other than that i was able to print for several days with no problems
Later, during one of the typical hotend clogs i damaged it irreparably, so i upgraded it to an e3d v6, reflashes the firmware with marlin 1.0 and few touches
Then it start failing with this very problem of losing the sync between where it was printing and so, exactly as described.
After banging my head several times over i found out that the culprit was the usb hub (wich powers a small usb fan, a wifi dongle and connects to solidoodle 2, nothing more)
Other problems were rare download failures and funny enough it was also hitting a bug in my adsl modem ocasionally it will kick out of the wifi all my machines at home :/
I strongly suggest to who may still suffer this problem is to check http://elinux.org/RPi_Powered_USB_Hubs where there is more info about the usb hub messyness w raspberry pi, among with isolated tests of the usb hub in itself

Hopefully this may save some evenings of unlucky guys

**Comment by MiregSan** [comment]
Any idea what happend? two times on same model at same percentage...

![bez nazvu](https://user-images.githubusercontent.com/33666029/32794502-5c4dc13c-c969-11e7-9403-f262d1ebbc9e.png)

**Comment by foosel** [comment]
If it happens at the exact same line I'd check if maybe your GCODE file contains that 0-byte garbage data already.

**Comment by MiregSan** [comment]
execuse me, how can i check this? every time it is stop at line about 217 000. i actualy try reslice and print again. same error at 220 000. 
here is the log file... [https://drive.google.com/open?id=1U6YllrvMqt9akYc0XszdnV5oZbT2Jx51](url) 

`2017-11-15 11:50:02,828 - octoprint.util.comm - INFO - Got a resend request from the printer: requested line = 224092, current line = 224093
| Last lines in terminal:
| Recv: ok
| Send: N224092 G1 X166.995 Y126.429 ?H  ?H  ?H  ?H  ?H   I      ?G  ,H  <H  ?G      H  *90
| Recv: Error:No Checksum with line number, Last Line: 224091
| Recv: Resend: 224092
| Recv: ok`
now i am printing from sd card. everythings works well...

**Comment by foosel** [comment]
It still looks like the file you are trying to print has some garbage data in there. Could you upload and share the file?

**Comment by MiregSan** [comment]
GCODE here... [https://drive.google.com/open?id=1ov6gH59isE1foNYA7SLYb4nrVGxxKXXT](url)

**Comment by PulgaFeroz** [comment]
>>now i am printing from sd card. everythings works well...

If the same file success when in SD card and fails when using the usb cable then it can be a hardware issue during I/O, try other usb port or another usb hub with the same failing file to discard your usb port / hub

**Comment by MiregSan** [comment]
It is possible low memory or high cpu usage? i use raspberry pi 1b. maybe pi 2 or pi 3 will be better? i have USB cable connected directly to pi without any hub. and i have installed no-ip on it.

**Comment by MiregSan** [comment]
And additional info for investigation - few day ago i was printing gcode around 3,5MB size and everything works well. Gcode which make error is 14MB size.

**Comment by PulgaFeroz** [comment]
my old rasp pi b model 1 did not work well directly connected to the printer + 1 wifi dongle, I then used a usb hub and had many problems until I realized that many usb hubs are NOT compatible with raspberry pi (specially the early models)  check  http://elinux.org/RPi_Powered_USB_Hubs
It is quite slow, my other printer runs in model b version 3 as is way way faster
I'd love to try the pi zero w (is only 10€ and has wifi built in!) and im sure it beats my old b rev 1

**Comment by PulgaFeroz** [comment]
if my memory serves me well, there are power issues with the PI in itself, I think back in the early days of PI it was recommended to use a powered usb hub to use a wifi dongle to alleviate the limitations of it, you're feeding the printer board thru the usb (in my case both the dongle and the printer)
also check the power source you're using with the PI (I think 2 amps was the recommended?)
To me your problem is quite similar to the one I had (an electric one, not a software one)

**Comment by MiregSan** [comment]
Ok, thanks for your help. I will try meassure power supply (2A), connect all USB via powered USB hub and then print again my gcode. I will post result here but propably during weekend. One more, thanks for your help and thanks mr.foosel for octoprint...

**Comment by foosel** [comment]
@MiregSan That doesn't appear to be the correct file. The line successfully sent just before the offending line is `G1 X139.78 Y65.376 E20052.55491` and that doesn't exist in the GCODE file that you shared. The comments in the header also state that it was sliced on 2017-11-14 19:48 and your log indicates an error with a file roughly 9 hours before that. If you don't share the *exact* file that produces the issue, it's impossible to determine if that file is at fault or not ;)

In general though, your printer communication is riddled with resend requests over and over again, hinting at some serious noise transmission. As already stated by @PulgaFeroz, that screams either power issues or connectivity issues caused by bad cables or wonky USB hubs. See also [the FAQ](https://github.com/foosel/OctoPrint/wiki/FAQ#octoprint-keeps-running-into-communication-errors-and-timeouts)

**Comment by PulgaFeroz** [comment]
May be a good idea to put a generic topic: Raspberry PI and Octoprint common issues, perhaps in the FAQ or so, this issue is rather popular and many of us fall prey to it.

It can be summed up like: powering the WIFI and/or your 3D printer directly from the PI instead of a powered usb hub can cause communication and/or printing issues.
Many usb hubs are NOT compatible with PI (see http://elinux.org/RPi_Powered_USB_Hubs)
Having long cables between the PI / printer / wifi dongle can cause problems
Not having adecuated power for your PI can also cause random printing problems (i/e http://www.aoakley.com/articles/2014-02-25-raspberry-pi-power-wifi.php)

You do get to learn a lot when facing those problems :)

-Mat

**Comment by foosel** [comment]
The FAQ is part of the wiki, which anyone with a Github account can edit ;)

**Comment by MiregSan** [comment]
I'm sorry, Mr Foosel. it's my fault, I uploaded a bad file. However, I know the new faults. My raspberry pi 1B now uses a 1.5A (1,09A consumption) power supply and the CPU temperature is over 90 ° C. as the first step I will deal with cooling, then I will return to the octoprint error. The temperature is, perhaps, the cause of the error.

**Comment by MiregSan** [comment]
Hi, i have new information for investigation. Now i try new raspberry pi zero ( temperature and power supply are ok).
Gcode around 3MB still print ok, but 12MB+, printer was stopped around 60%. I try to find answers and i think, my problem is same as issue 444. When i dissable gcode visualizer, my octoprint work like a charm...

https://github.com/foosel/OctoPrint/issues/444

**Comment by foosel** [comment]
No, you probably do not have the same issue as #444 since that was reported as client-side only with completely different symptoms and your communication errors arise in the backend. The GCODE viewer downloads the full file to the frontend and then operates strictly inside your browser. I don't see how that could be causing resend errors in your backend.

If you disable the GCODE viewer and your printer communication starts working flawlessly, that's either coincidence, or caused by some weird resource consumption leading to brown-outs. E.g. you running the GCODE viewer on the same machine that OctoPrint itself is running on.

If you want help with this, I suggest you provide an **exact** file (ideally outright downloaded from your OctoPrint instance) you are having issues with, together with a [**serial.log**](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md#where-can-i-find-those-log-files-you-keep-talking-about) of the issues you are having.

PS: And in the future, please don't drag up ancient tickets but instead first ask for help [on the established support channels](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md#issues-tickets-however-you-may-call-them). This is not a support forum but an issue tracker :)
