### ISSUE TITLE
[Request] Setup for using your own logos on graph and timelapse video

### ISSUE THREAD

**Issue by henrikkoch** [foosel/OctoPrint#1726]
Please make it possible to put your own logo on both the Temperature graph and on the timelapse videos. Its very easy just to exchange the files but on every update this these changes are lost.

The need for own logos are when your print something for others f.ex. on 3DHubs Then I can be a good thing to "brand" it with your hub name.

**Comment by foosel** [comment]
Sorry, but this is something I'm not going to implement.

I understand your wish of branding your instance for business reasons. That should also help you to understand my wish to keep the current recognisable branding on the officially supported version since it is the only way for me to generate brand awareness (which directly helps to finance my full time work on this software by word of mouth).

If you want a custom branded version, feel free to get in touch, we might be able to work something out.
