### ISSUE TITLE
Add "Test" button to webcam config [WAS: error check snapshot for timelapse]

### ISSUE THREAD

**Issue by fehknt** [foosel/OctoPrint#183]
Was puzzling over my broken timelapse for a while, had all these broken 3k jpeg files created with no errors until transcoding.  Turns out that it just downloaded the default mjpeg-streamer webpage that shows up for any action that is not prefixed with a valid action.

I'm thinking that something along these lines for console debugging might be nice?
http://stackoverflow.com/questions/266648/python-check-if-uploaded-file-is-jpg
(With or without the preview image)

Thoughts?  Happy to implement / pull request, I like Python.

**Comment by foosel** [comment]
![image](https://cloud.githubusercontent.com/assets/83657/10246827/d47bccce-6914-11e5-8425-b13c8108c5e4.png)

![image](https://cloud.githubusercontent.com/assets/83657/10246818/c68ff09a-6914-11e5-8d54-c96ccee879d1.png)

![image](https://cloud.githubusercontent.com/assets/83657/10246832/de2bbc3e-6914-11e5-9c11-fa846a8ea453.png)

Totally forgot to close this ticket - test buttons for both the snapshot and the stream are now implemented in `devel`. Client side. Will be included with the 1.3.x release (I will probably not backport it to 1.2.x since it needs a bunch of new stuff to work).
