### ISSUE TITLE
OctoPrint issues with Webcam

### ISSUE THREAD

**Issue by RodneyMcKay715** [foosel/OctoPrint#1851]
#### What were you doing?
I installed Octoprint and set it up like in the installation instructions on the github page.

#### What did you expect to happen and what happened instead?

If i start octoprint there is an issue. Sometimes everything works fine, little to no delay in the camera and good reaction time in the Web UI, but sometimes it just starts to lag horribly. At first i thought it was the Pi itself, but i dont know. If it starts to lag, i get the Popup, that a new server version has been detected and the pi starts over and over again for about 3 times. The other scenario is, where this doesnt happen that the camera is delayed 15-20 seconds, like in the Video shown in my Github issue report. The last scenario is that Octoprint just says "The Server has been shutdown" if i click any Menu Entry ( for example terminal)
The funny thing is however, that if i access the stream directly over <Pi IP>/webcam/?action=stream its fluid and has no issues. As soon as i use it in combination with the Web interface the Interface begins to behave delayed and is constantly loading something and the stream starts to lag.Also it needs about 30 seconds to fully load up (tested with and without haproxy as well.) and even that is not guaranteed. Sometimes it just loads the upper bar and thats it, other times its loaded instantly.If it doesnt load, the Pi is still fully accessible over SSH. My router is a FritzBox 3270 , my PI is an Raspberry PI 3 Model B not overclocked, using only the command line. What  is weird however is that it barely uses any CPU capacities. It uses 0 - 3% cpu if running the camera stream (original raspi cam) and octoprint together.
This issues happen with Raspbian Lite, Raspbian+ Pixel, OctoPi and an manual OctoPrint installation.

#### Branch & Commit or Version of OctoPrint
1.3.2 master branch

#### Operating System running OctoPrint
Raspbian Jessie Lite

#### Printer model & used firmware incl. version
Anet A6 with Skynet 2.3.1
[If applicable, always include if unsure.]

#### Browser and Version of Browser, Operating System running Browser
Firefox 52.0.1 Win7 64 bit

#### Screenshot(s) showing the problem:

I created 2 youtube videos.
One with the Usage of HaProxy:
https://www.youtube.com/watch?v=R9JRTMopaWg

The Other without HaProxy over direct Link:
https://www.youtube.com/watch?v=bB5B771TQFs

Just to get a picture of what i mean with lag/delay.
I have read the FAQ.

**Comment by foosel** [comment]
> the pi starts over and over again for about 3 times

As I already stated in #1846, sudden restarts of the Pi indicate a serious issue *outside of software*. Based on past experiences your observed symptoms sound like your Pi is not getting enough power and browning out when a bit of strain is put on the system.

All your issues sound like either power or network problems. This is nothing that can be solved in software, least of all by OctoPrint. Please seek support on the [mailing list](https://groups.google.com/group/octoprint) or the [G+ Community](https://plus.google.com/communities/102771308349328485741), maybe someone there has more ideas on what else you could try. But the bug tracker is the wrong place for this - there is no bug here, it's the system under OctoPrint that is acting up here, not OctoPrint.

Also - you continue to remove bits and pieces from the ticket template. In the future please **always provide all information that is asked for**, it's asked for for a reason. For example, none of your tickets so far provided the requested `octoprint.log`, which is **absolutely crucial** for any kind of analysis, nor the output on the JavaScript error console. It is kinda frustrating and extraordinarily time consuming having to run after this type of information all the time, which is why the ticket template is in place and why it requests this log among other things.

I'm closing this because - again - based on the information you gave this is not an issue with OctoPrint but with the system you are running it on, which behaves unstable and erratically. Please stop opening new tickets about this particular issue, seek support on the [mailing list](https://groups.google.com/group/octoprint) or the [G+ Community](https://plus.google.com/communities/102771308349328485741) instead if checking the power supply does not help - and when seeking support there be sure to **supply logs**.
