### ISSUE TITLE
404 error - Failed to load sockjs.js.map

### ISSUE THREAD

**Issue by klcjr89** [foosel/OctoPrint#1924]
**What were you doing?**

Viewing the javascript console in Safari

**What did you expect to happen and what happened instead?**

I expect there to not be a 404 error, but there was.

**Branch & Commit or Version of OctoPrint**

Devel

**Operating System running OctoPrint**

OctoPi

**Browser and Version of Browser, Operating System running Browser**

Safari 10.1.1 on macOS 10.12.5

I have read the FAQ.
<img width="1177" alt="ss" src="https://cloud.githubusercontent.com/assets/1977032/26206394/b2cb816a-3bb2-11e7-99e8-1284bcb3c5b1.png">

**Comment by foosel** [comment]
I couldn't reproduce this (for some reason neither Chrome nor Firefox did want to show me any information regarding referenced source maps loading or not loading), but I fixed it anyhow, even though it's merely "a bit ugly" but not really a problem - source maps are a debugging tool and not relevant for the functionality of the UI. 

Since source map resolution is wonky in combination with assets bundled through webassets, OctoPrint now strips source map references from bundled JS files. Additionally though I also added the source map for sock.js to the sources, just in case someone includes that js file directly (e.g. from a custom UI).

Relevant commits are 832c27ed18bd84b517a2b6de824cd9a96995ce7d and cfde6342a824712169cc7b6f9170c6e536b2a508 which should be available on `maintenance` and `devel`.

A quick report on whether that indeed solves this for you would be nice, since I couldn't trigger such an error in the browser console myself.

**Comment by ntoff** [comment]
>I couldn't reproduce this (for some reason neither Chrome nor Firefox did want to show me any information regarding referenced source maps loading or not loading)

I see nothing but 404's in what I guess is stdout? the terminal windows thing when you run octoprint from a command prompt (what I assume ends up in octoprint.log). Not so much in chrome's console though.

**Comment by foosel** [comment]
1.3.5 was released yesterday.
