### ISSUE TITLE
USB camera

### ISSUE THREAD

**Issue by szerwi** [foosel/OctoPrint#1932]
#### What were you doing?
I'm trying to connect usb camera (Logitech C920) to the OctoPrint by typing "./mjpg_streamer -i "input_uvc.so $-r VGA -f 10" -o "output_http.so -w ./www"" in Stream URL tab, but it's not working.

#### What did you expect to happen and what happened instead?

I thought it will display the view from the camera, but nothing happens.

#### Branch & Commit or Version of OctoPrint

OctoPrint 1.3.2 (master branch)

#### Operating System running OctoPrint

Windows 10

#### Printer model & used firmware incl. version

Anet A8, Skynet3D

#### Browser and Version of Browser, Operating System running Browser

Windows 10, Google Chrome

#### Link to octoprint.log

https://pastebin.com/iDE9DbJf

#### Link to contents of terminal tab or serial.log

-

#### Link to contents of Javascript console in the browser

-

#### Screenshot(s) or video(s) showing the problem:

[If applicable. Always include if unsure or reporting UI issues.]

I have read the FAQ.

**Comment by foosel** [comment]
Quoting the [FAQ](https://github.com/foosel/OctoPrint/wiki/FAQ#my-webcam-is-not-working):

> **My webcam is not working!**
>
> OctoPrint doesn't directly control your webcam. All it can do is embed an MJPG stream into the web interface and retrieve snapshots for the timelapse frames from the configured snapshot URL. If your webcam isn't working, it isn't something OctoPrint is at fault for or can fix.

So this bug tracker for OctoPrint is the wrong location for seeking help with this, the Mailinglist or the G+ Community as the bot already linked you to in #1931 are better locations.

That being said

> I'm trying to connect usb camera (Logitech C920) to the OctoPrint by typing "./mjpg_streamer -i "input_uvc.so $-r VGA -f 10" -o "output_http.so -w ./www"" in Stream URL tab, but it's not working.

That's not a Stream URL, that's a command line to fire up the webcam stream server if you have it installed manually. You haven't specified if you have installed OctoPrint manually or are using OctoPi. OctoPi already comes fully preconfigured and your webcam model *should* just work when you plug it in, the correct Stream and Snapshot URLs can be found [in the FAQ as well](https://github.com/foosel/OctoPrint/wiki/FAQ#how-do-i-have-to-configure-the-webcam-urls-in-octoprint-so-that-everything-will-work) - make sure to reset them to the correct value if you run OctoPi.

I suggest the following: Post to the G+ Community or the Mailinglist, describe your setup (OctoPi? What version? If not OctoPi, how else have you OctoPrint setup? The more details here the better), describe as detailed as possible what you are seeing (e.g. does the camera LED come on or not), what you have already tried and what guides you've followed to get where you are now.

But please do not open yet another ticket in this bug tracker, your problem is a support issue, NOT a bug, and hence this is the wrong location.
