### ISSUE TITLE
[Request] Reverse second extruder option.

### ISSUE THREAD

**Issue by Pueltamika** [foosel/OctoPrint#1992]
Hi,

I recently bought a BCN3D Sigma R17, a printer with a independent dual extruder.
For some reason they decided to mirror the second extruder, changing the direction of the steppermotor.
Printing with an SD card using the printers own software works, but the direction of the filament is reversed when using Octoprint.
The obvious option is to reverse the wiring of the printer, but the printer will lose it's ability to load and unload it's filament, or cabilbrate the hotends.

Could it be possible to have a checkbox in the printer settings of octoprint to reverse the direction of the second extruder?

Yours sincerely,

Pueltamika

Attachments: Left and right extruder.

![20170510_110810](https://user-images.githubusercontent.com/29861776/27791256-71a30d1e-5ff4-11e7-82dd-dfec251bc657.jpg)
![20170510_110817](https://user-images.githubusercontent.com/29861776/27791257-71a7810a-5ff4-11e7-9edc-08c9201fc6d7.jpg)

**Comment by lf-** [comment]
Can you fix this in the slicer?

**Comment by foosel** [comment]
If the same GCODE from SD works but streamed from OctoPrint doesn't, you're most likely missing something in your start GCODE that would tell your printer's firmware to reverse the coordinates it receives (some EEPROM value maybe?) that it does add automatically when printing from its internal SD.

While something like reversing every single extrusion line could be done through OctoPrint, it would add *significant* processing overhead, increasing the likelihood of stuttering and negative quality impact severely. There is a reason OctoPrint keeps its hands off of GCODE sent through it and just relies on it being fitting for your printer (as the corresponding configuration options say, all the things like motor direction and such in the printer profile are only used for stuff like the Control panel or making sure the GCODE analysis and viewer behave - it's NOT for modifying files streamed through OctoPrint on the fly!).

Instead you should try to figure out what your printer's firmware does differently when printing from SD vs. when it receives GCODE move commands through the serial connection, and add whatever it's missing either to your slicer or OctoPrint's own start GCODE script.

Closing this because it's simply entirely impractical to allow inverting certain coordinates for files streamed through OctoPrint. It might be possible to write a plugin to solve this, but I highly recommend against it due to the aforementioned performance reasons.
