### ISSUE TITLE
File drop area keeps vanishing

### ISSUE THREAD

**Issue by Lenbok** [foosel/OctoPrint#202]
When I drag a gcode file over the window, initially the dark grey file drop area shows up, but it then vanishes until I wiggle the mouse some more. Happens with both firefox and chrome, on ubuntu 12.04. Octoprint commit
407c61cb2422bb6d43ac16f2809ef79c642c2603

**Comment by foosel** [comment]
Couldn't reproduce at all, might have been fixed though by simply changing around stuff for other things. Please reopen if it still occurs for you.

**Comment by eyal0** [comment]
I'm seeing this issue, too, on multiple computers.  All are Ubuntu Linux using Chrome.

I'll work on it.

**Comment by foosel** [comment]
@eyal0 hmm, ok, reopening it then. I still haven't been able to reproduce it all, but if you are able to somewhat reliably reproduce it, maybe we can get this narrowed down together!

**Comment by eyal0** [comment]
Okay, I'm able to reproduce it and I understand the issue.  The problem is in [files.js](https://github.com/foosel/OctoPrint/blob/master/src/octoprint/static/js/app/viewmodels/files.js#L1095).  There is a timer that causes the file upload overlay to disappear after 100ms.  Ideally, the `dragover` event continues to trigger faster than that and there is no problem.  But, when the mouse is dragging but not moving, dragover only triggers once every 350ms, [according to this webpage](https://www.w3schools.com/jsref/event_ondragover.asp).

One solution is to modify the above line from 100 to 400.  400 is safely above 350ms.  I tested this on my computer and it works.  However, 400ms is slow and the webpage becomes a little clunky.

A better solution is to use dragenter and dragleave.  It's tricky because a dragleave event occurs when the overlay appears to so you can't just hook dragleave.  You need to make sure that it's dragleave of the most recent dragenter.  I'll write a PR for that.  In the meanwhile, try changing 100 to 400 and see how you like.  If it's good enough for you, okay.  If it's too slow then the dragleave solution is more complicated but much nicer.
