### ISSUE TITLE
Select active tab using hash from URL.

### ISSUE THREAD

**Issue by JoshMcCullough** [foosel/OctoPrint#203]
For instance: http://myprinter/#control should show the Control tab by default. I see that there are anchor tags in place for each tab, but they are not pre-selected when the hash changes.

**Comment by TTN-** [comment]
Any word on if there is a commit that has fixed this yet? If there is, I'd be keen to start using it :-)

**Comment by Salandora** [comment]
No no updates yet, will tackle this one on Sunday.

**Comment by eyal0** [comment]
This is really great!  Why isn't it being merged into releases?

**Comment by foosel** [comment]
Because it was done against `devel`. But good point, makes sense to cherry pick this.

**Comment by foosel** [comment]
Cherry picked to `maintenance`, will be part of 1.3.6.

**Comment by eyal0** [comment]
Would you also consider this change: https://github.com/eyal0/OctoPrint/commit/c9b396fd33c7dfaec99ba1247a084f695dfc1cb6

It makes it so that the URL bar updates when clicking on a tab.  Here are somethings that I tested and their expected result:

1. Click on a tab: Tab changes and the URL changes to include the tab's identifier (eg, "#gcode")
2. Middle-click on tab: New browser window opens with the middle-clicked tab showing.
3. **Copy-paste URL into a new browser window: New window shows the same tab as the previous window.**
4. Click back button: Return to previous website (ie, github), even if lots of tabs have been clicked and the URL has changed a lot.

Number 3 didn't work before c9b396fd33c7dfaec99ba1247a084f695dfc1cb6.

If you want me to make a PR for the above commit (it's only 3 lines) then let me now what branch to do it for and I'll do it.

**Comment by foosel** [comment]
Hm... Right with the cherry picking I did follow it up with 3cf694a33339a4f01f3f63a5825329ed72d4e5fc, intentionally letting the hash changes going to the history because that allows stuff like very quickly toggling back and forth between two tabs through the browser history (and thus something like the side buttons on your run-off-the-mill five button mouse).

Has the same result as your's minus point 4 (again, that's intentional).

**Comment by eyal0** [comment]
Okay. Can't wait to pick it up in the next release!  Thanks.

**Comment by foosel** [comment]
Closing because 1.3.6 was just [released](https://octoprint.org/blog/2017/12/12/new-release-1.3.6/).
