### ISSUE TITLE
Object doesn't fit print volume

### ISSUE THREAD

**Issue by Cyphen-Cyn** [foosel/OctoPrint#2047]
I am receiving this error.

"Object doesn't fit print volume
Object in Bed_Level_Calibration.gcode exceeds the print volume of the currently selected printer profile, be careful when printing this."

OctoPrint version 1.3.4 (Master Branch)

Slicing in Simplify 3D version 4.0

Printer Replicator 1 dual

[Bed_Level_Calibration.txt](https://github.com/foosel/OctoPrint/files/1185988/Bed_Level_Calibration.txt)

**Comment by WarpZoneNL** [comment]
Same here!

OctoPrint: 1.3.5rc2

**Comment by JohnOCFII** [comment]
Does your printer do a priming strip outside the normal printing area (the Prusa i3 MK2 does, for example.  If so, you'll want to add a custom bounding box under Settings -> Printer Profiles -> <YourProfile>.

So, for example, the MK2 goes negative on Y for the priming strip, so my custom bounding box is:

```
X Coordinates: Min: 0 Max 250
Y Coordinates: Min -4 Max 210
Z Coordinates: Min 0 Max 200
```

**Comment by Cyphen-Cyn** [comment]
John, 

the prime strip seems to be fully on the print bed.

I actually checked the g-code preview in Octoprint and it shows the whole print offset from center by at least 30% to the bottom left. However it will print without messing up. is there a setting i am missing somewhere or is this a bug?

**Comment by foosel** [comment]
@Cyphen-Cyn @WarpZoneNL unless done already please provide:

  * sample GCODE file with which to reproduce (still needed from @WarpZoneNL)
  * configured printer profile data (bed width, depth, height, custom bounding box values, extruder count & offsets) (still needed from @Cyphen-Cyn and @WarpZoneNL)

**Comment by ogoudge** [comment]
I am having this same issue with larger prints but still well with in the bed volume. I have found that if I upload the gcode and print I have no issues. However if I do anything else then come back to it I get this error. The work around has been to delete the file and re-upload it and print it right away. This has happen on more then one file now.

**Comment by ogoudge** [comment]
As an update! I have to printers setup with Octoprint both are doing the same exact thing.

**Comment by WarpZoneNL** [comment]
@foosel 

Sorry for my late reply, holliday ;-) 

![prusa1](https://user-images.githubusercontent.com/16835124/29918214-ed9ffe44-8e44-11e7-9a7c-0d48efdede86.JPG)
[small_bed.gcode.txt](https://github.com/foosel/OctoPrint/files/1266680/small_bed.gcode.txt)
![capture](https://user-images.githubusercontent.com/16835124/29918215-eda6940c-8e44-11e7-8e15-9aff00a07be3.JPG)

**Comment by foosel** [comment]
@WarpZoneNL I tried to reproduce this with your file against 1.3.5 and a printer profile for a MK2 with properly configured custom bounding box to compensate for the out-of-bed priming - I can't. No warning, everything detected fine. I also noticed that your printer profile editor still seems to be all on one page - that hasn't been the case since OctoPrint 1.3.0rc1 actually, so this looks like you are running a fairly old 1.2.x version there and chances are high the issue you are experiencing has already been fixed for some time. Please check if you can reproduce it under 1.3.5.

@Cyphen-Cyn @ogoudge I can't look into this further without
  * a file with which to reproduce this (still needed from @ogoudge)
  * configured printer profile data (bed width, depth, height, custom bounding box values, extruder count & offsets - **all** of that, not just bits please) (still needed from @Cyphen-Cyn and @ogoudge)

**Comment by foosel** [comment]
Closing due to lack of response.
