### ISSUE TITLE
Octopi or Octoprint requires reading the canvas to show temperature graph

### ISSUE THREAD

**Issue by oUToWEROfeCtICIonselMOni** [foosel/OctoPrint#2224]
----

#### What were you doing?
Octopi/OctoPrint seems to require read access of the canvas (a web technology) to display the temperature graph.  When I set CanvasBlocker 0.4.2 to prompt me whenever something tries to read the canvas, and deny the request, Octoprint will show me the temperature graph.  However, if I only allow the whitelist, if Octopi.local is not in the list, I do not see any data for the temperature graph.  If I whitelist Octopi.local, I see the temperature graph like normal.

#### What did you expect to happen?
That neither Octopi nor OctoPrint require access to the canvas, nor try to read it.  Reading the canvas is a tracking technique, why is Octoprint using it?

#### What happened instead?
Temperature graph stopped working.  The rest of the UI works fine*.

#### Did the same happen when running OctoPrint in safe mode?
N/A?

#### Branch & Commit or Version of OctoPrint
Ocroprint 1.2.7
I know it's kind of old, but it can't update itself for some reason.  However, unless you've specifically fixed this, I don't think it's going to be fixed in a later release.  This is more of a design "problem" than a bug.  Someone somewhere decided to read the canvas, and I'd like you to undecide to do so.  plz/thx.

#### Operating System running OctoPrint
Octopi 1.2.7

#### Printer model & used firmware incl. version
N/A, it's a web technology problem.

#### Browser and Version of Browser, Operating System running Browser
Firefox 56.0.2
CanvasBlocker 0.4.2

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by foosel** [comment]
OctoPrint uses [flot](http://www.flotcharts.org/) for the temperature graph, which is a graphing library utilizing the HTML5 canvas technology. 

The only reference to a canvas "readout API" I could find was in the CanvasBlocker extension itself and apparently what they consider the "readout API" are the functions `toDataURL`, `toBlob`, `mozGetAsFile`, `getImageData`, `readPixels` - none of which are used in either flot or the temperature graph code in OctoPrint. In fact, only `toDataUrl` is even present in the whole OctoPrint code base - in the Jquery QR code plugin used for presenting the user's API key as a scannable QR code. 

OctoPrint doesn't perform any fingerprinting or tracking (and if any of that changes in the future it will be strictly with the user's consent) - you don't have to trust me on that, the source is open, feel free to audit it. I cannot guarantee the same for any third party plugins you might have installed though. In any case, if you intentionally cripple general canvas functionality in your browser due to fear of fingerprinting, it is to be expected that stuff stops working as designed.

> Ocroprint 1.2.7
> I know it's kind of old, but it can't update itself for some reason.

I suggest you take a look at [the FAQ](https://github.com/foosel/OctoPrint/wiki/FAQ#im-running-127-i-tried-to-update-to-a-newer-version-via-the-software-update-plugin-but-im-still-on-127-after-restart).
