### ISSUE TITLE
[Request] Gcode Viewer: show printing head location with a marker/pointer.

### ISSUE THREAD

**Issue by jvalrog** [foosel/OctoPrint#2318]
Is it possible to add an option to show where the printing head is currently? A simple marker would be nice.

I'm attaching a mockup of the feature.

Thanks for this awesome piece of software.
![2017-12-25-115828_2560x1080_scrot](https://user-images.githubusercontent.com/456311/34339487-af96627c-e96c-11e7-8c74-44325cbfb0e8.png)

**Comment by ntoff** [comment]
Since most printers don't offer any kind of feedback, the host doesn't know exactly where the print head is at any given point. The printer has an internal buffer that's slightly behind what the host sends and marking the head's position on the gcode viewer wouldn't necessarily be in sync with where it actually is.

**Comment by jvalencia80** [comment]
It doesn't need to be perfect, it can be drawn on the last point of the current segment. Sometimes you just don't know where is it.

**Comment by foosel** [comment]
Implemented in the above commit. Available on `maintenance`, soon `devel`, to be released with 1.3.9.

![image](https://user-images.githubusercontent.com/83657/39662574-f84d936a-5063-11e8-92cf-d75cb011de49.png)
