### ISSUE TITLE
Sudden error starting up OctoPrint

### ISSUE THREAD

**Issue by mullinsen** [foosel/OctoPrint#2477]
#### What were you doing?

I tried to start the OctoPrint server. Has worked fine until now.

#### What did you expect to happen?

The OctoPrint server to start.

#### What happened instead?

A list of errors (Listed in link to octoprint.log. Not sure that was correct, I am new to this)

#### Version of OctoPrint

Latest (Already Tried update and Upgrade).

#### Operating System running OctoPrint

Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux

#### Printer model & used firmware incl. version

N/A

#### Browser and Version of Browser, Operating System running Browser

N/A

#### Link to octoprint.log

https://gist.github.com/mullinsen/f6f83cb3f8a1c0267cadec8b18a76dfe

#### Link to contents of terminal tab or serial.log

N/A

#### Link to contents of Javascript console in the browser

N/A

#### Screenshot(s)/video(s) showing the problem:

N/A

I have read the FAQ.

**Comment by foosel** [comment]
Looks like your install has become corrupted. This can happen if you pulled power from the Pi without shutting it down properly first or if the file system has become corrupted for other reasons (e.g. the SD card slowly dying). 

Not a bug or something that OctoPrint can do anything about.

Since this might not be the only thing that got corrupted, reflashing (preferably on a new card) might be your best bet here. You can also try a reinstall of course but YMMV.
