### ISSUE TITLE
Can't update from 1.3.4 to 1.3.6

### ISSUE THREAD

**Issue by CrazyCitystars** [foosel/OctoPrint#2523]
#### What were you doing?

Updating the octoprint from a clean install

#### What did you expect to happen?
Updating

#### What happened instead?
Didn't update

#### Did the same happen when running OctoPrint in safe mode?

Can't updating in safe mode i think?

#### Version of OctoPrint
1.3.4

#### Operating System running OctoPrint

Octopi 

#### Printer model & used firmware incl. version

Tevo Tarantula with marling easy bugfix 1.1

#### Browser and version of browser, operating system running browser

Chrome Version 65.0.3325.181 (Official Build) (64-bit)

#### Link to octoprint.log

https://gist.github.com/CrazyCitystars/2b0f2cc56464ece1706952072cd37a47

#### Link to contents of terminal tab or serial.log

https://gist.github.com/CrazyCitystars/2b0f2cc56464ece1706952072cd37a47

#### Link to contents of Javascript console in the browser

This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.
packed_core.js?abf24465:12820 Starting dependency resolution...
packed_core.js?abf24465:12921 ... dependency resolution done
packed_core.js?abf24465:13150 Initial application setup done, connecting to server...
packed_core.js?abf24465:11368 Connected to the server
packed_core.js?abf24465:13154 Finalizing application startup
packed_core.js?abf24465:13058 Going to bind 28 view models...
packed_core.js?abf24465:13099 Did not bind view model CoreWizardAclViewModel to target #wizard_plugin_corewizard_acl since it does not exist
packed_core.js?abf24465:13099 Did not bind view model CoreWizardPrinterProfileViewModel to target #wizard_plugin_corewizard_printerprofile since it does not exist
packed_core.js?abf24465:13099 Did not bind view model CoreWizardWebcamViewModel to target #wizard_plugin_corewizard_webcam since it does not exist
packed_core.js?abf24465:13099 Did not bind view model CoreWizardServerCommandsViewModel to target #wizard_plugin_corewizard_servercommands since it does not exist
packed_core.js?abf24465:13099 Did not bind view model CuraViewModel to target #wizard_plugin_cura since it does not exist
packed_core.js?abf24465:13099 Did not bind view model SoftwareUpdateViewModel to target #wizard_plugin_softwareupdate since it does not exist
packed_core.js?abf24465:13132 ... binding done
packed_core.js?abf24465:13143 Application startup complete

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by foosel** [comment]
```
error: [Errno 30] Read-only file system <built-in function rmdir> /tmp/easy_install-kDXvh2
```

That's the underlying python `easy_install` complaining about something being up with your file system. That's outside of the control of OctoPrint. A fresh OctoPi 0.14 on a good SD running on a Pi with adequate power supply doesn't run into this error (and I'm 100% sure about this because I spent last friday running through about five installs + updates while testing 1.3.7rc2).

I suggest you try to reflash, preferably on a fresh SD (reliable brand, Class 10). If it still doesn't work, best get in touch [the community forum](https://discourse.octoprint.org) - this doesn't look like a bug but rather a problem with your specific setup.

PS: 

> Can't updating in safe mode i think?

You can. Safe mode keeps bundled plugins enabled, the software update plugin is bundled.
