### ISSUE TITLE
settings not saved

### ISSUE THREAD

**Issue by sfornengo** [foosel/OctoPrint#2555]
#### What were you doing?

My settings (connection port, printer profile, webcam, ...) are not saved... each time I switch off my pi then my settings are lost. Even if I update to last octoprint version (1.3.7-rc4) if I switch off my pi it reboots under 1.3.6

#### Version of OctoPrint

1.3.7-rc4

#### Operating System running OctoPrint

     OctoPrint 1.3.7rc4 running on OctoPi 0.14.0

#### Printer model & used firmware incl. version

tevo tornado

#### Browser and version of browser, operating system running browser

firefox

#### Link to octoprint.log

https://gist.github.com/sfornengo/0afd02fe80d10e86bd075316bef84cc3

**Comment by foosel** [comment]
> Even if I update to last octoprint version (1.3.7-rc4) if I switch off my pi it reboots under 1.3.6

That and your vanishing settings sounds more like a broken SD card. Could be easily caused by not shutting down the Pi *properly* through the system menu before powering it off. Never just cut power, always shut it down properly or you will lose data.

Verify that your SD card is not corrupted (try another one maybe, run `fdisk`, etc). If that doesn't solve it open a thread in the [community forum](https://discourse.octoprint.org/c/support) please - this definitely sounds more like an issue unique to your installation than a bug.
