### ISSUE TITLE
[Request]  Disable animation for critical dialog boxes

### ISSUE THREAD

**Issue by combs** [foosel/OctoPrint#2597]
Hello! When I am trying to stop my printer at a critical moment, the "Are you sure?" dialog's animation gets in the way. Sometimes I go for the button before it's stopped moving and accidentally click the background behind the modal, which auto dismisses it. 

I know it's only about a second but I wonder if you might make the animation optional. 

Thank you for your time and your hard work maintaining this software.

Regards,
Chris

#### Version of OctoPrint

OctoPrint 1.3.6 running on OctoPi 0.14.0

#### Operating System running OctoPrint
OctoPrint 1.3.6 running on OctoPi 0.14.0

#### Screenshot(s)/video(s) showing the problem:

![screen shot 2018-04-19 at 20 06 47](https://user-images.githubusercontent.com/6174018/39024199-4519976a-440d-11e8-95fd-52d3ebee1246.png)

I have read the FAQ.

**Comment by ntoff** [comment]
Why not turn it off? Go to the features section and disable the confirmation on cancel.

**Comment by foosel** [comment]
Closing due to lack of response and ability to disable in the settings. Also, the cancel button isn't the best solution for emergencies. Install one of the emergency button plugins that are betters suited for actual emergencies.

**Comment by combs** [comment]
I feel that there is middle ground between "making it possible to accidentally cancel with one click" and. "watching a dialog slide from the top of the screen for a full second." I was not aware that I needed to respond to the earlier suggestion since it doesn't solve my problem. 

I would constructively encourage the team to thoughtfully consider the use of animation @foosel @ntoff. In my view a slide from the top doesn't make sense for an interruptive modal; a zoom from the center or no animation at all is much more the norm.

Thank you for your role in providing this software to the world.

**Comment by ntoff** [comment]
>I would constructively encourage the team to thoughtfully consider the use of animation 

and I would constructively encourage you to actually discuss issue tickets with people who offer solutions, rather than flat out ignore them and disappear if the solution isn't to your liking. How were we to know my offering wasn't a viable solution? You literally ignored the thread for a month with no feedback at all and so it was considered another "drive by" ticket, where people fly in, post something, then are never seen again.

**Comment by combs** [comment]
Bit of a hostile response there.

**Comment by foosel** [comment]
He has a point though. I do get a *LOT* of "drive by" feature requests here. It's hard to decide on what to include and what not and how best to do it when the person who requested it doesn't react to requests for clarification. That strongly signals "I'm not actually interested in getting this realized" based on past experience. And this is not feasible because:

> the team

The team is severely resource restricted - look into the commit history and you get an idea why. I have my hands full with a ton of stuff that concurrently screams for my attention. I try to cater to all of those, but that also requires a certain kind of collaboration from whoever seeks responses. As in, not dropping off the radar, especially after presented with an already working solution to a feature request. Respect goes both ways.

**Comment by combs** [comment]
Thank you

**Comment by ntoff** [comment]
>Bit of a hostile response there.

Sorry if it seemed that way, but also to be fair your "I didn't know I needed to respond since the solution wasn't to my liking" also sounded quite snobby, as if us mere mortals aren't worthy of being replied to by one such as high as yourself.

**Comment by brnl** [comment]
Thanks @foosel! I am really happy with that!
For me, all the animations might have been turned off. I like it raw :-P
