### ISSUE TITLE
[Request] "all or nothing" Plugin-Update

### ISSUE THREAD

**Issue by OllisGit** [foosel/OctoPrint#2615]
Hi,
if octoprint detects that a plugin has a new release, it shows a popup.
Sometimes I turned off my printer for weeks and after reusing it, octoprint shows me all new releases of a plugin.
It would be very nice, if it's possible to select each single plugin for an update.
At the moment there is only an "all or nothing" approach.

What do you think?
Olli

#### Version of OctoPrint
OctoPrint 1.3.6+

#### Screenshot(s)/video(s) showing the problem:

![f1bc1fbd185a2e1637877964f45bff3d07f4373a](https://user-images.githubusercontent.com/24205767/39404782-1ee29b48-4b9a-11e8-91ca-645d501cbd90.png)

**Comment by ntoff** [comment]
What about check boxes next to each plugin that you can tick or untick and then the update button will only update the plugins that are marked for update.

**Comment by markwdickson** [comment]
I was just coming here to request the same feature. I think a good, and hopefully easy to implement option, would be to allow individual `Update` buttons on the line items displayed in the `Software Update` panel of the `Settings` dialog. The attached image shows what I am talking about.  I think it would also be nice to have an `Update All` button available directly here, rather than the clunky feeling `Check for Updates` and then clicking update from a popup notification.

I was originally thinking of having check boxes next to the line items, but given the potential for pagination if you have a lot of plugins, that seems like it might become problematic with "hidden" selected updates.

What do you think?

![image](https://user-images.githubusercontent.com/1031162/39458150-7af70fc8-4cc0-11e8-8077-283b09841cab.png)

**Comment by jneilliii** [comment]
I like this approach, keeping the advanced update options contained within settings vs putting check boxes on the pop-up notification. And if this gets put int the queue for changes, it would be nice to implement the reset to default settings I saw mentioned on the community forum as well.

**Comment by ntoff** [comment]
Agreed, simple popup with the advanced stuff being hidden away. Much better  than my idea. Perhaps a message on the popup though: "To update plugins individually, see the software update section of the settings" ? Just so people know it exists.

**Comment by foosel** [comment]
Was fairly easy since the backend already did support selective updating, I just never added it to the UI. Really liked the idea of @markwdickson so there you go ;)

![image](https://user-images.githubusercontent.com/83657/39663630-ebfbe59a-5076-11e8-9a92-2f6ae11485c4.png)

Just pushed to `maintenance`, soon `devel`, to be released with 1.3.9.

**Comment by markwdickson** [comment]
That's awesome!  Looking forward to 1.3.9.  Thanks @foosel
