### ISSUE TITLE
Request: Allow controll of I/O header of the RPi

### ISSUE THREAD

**Issue by dumle29** [foosel/OctoPrint#273]
It would be very very neat if there could be access to the I/O of the RPi. I am using sanguinololu and occasionally print from the SD card with an LCD attached. Having an LCD+SD+Encoder on a Sanguinololu means that you use every single I/O pin available to you.

My idea is to read the G-code files uploaded, and then look for any custom O commands. These O commands should triger special functions in octoprint, just like M triggers special functions in marlin.

This will allow one to add "O23 1" As an example to turn on I/O pin 23 which I would then have connected to a mosfet controlling a relay that turns on/off the power to my printer. You could also have commands like O201 (Or whatever) That would take a snapshot.

**Comment by AndKe** [comment]
@bubbasnow  - I get  "-bash: gpio: command not found"  - on a recent install,   did you do anything to install gpio  ?

**Comment by Nikasio14** [comment]
Hi there, 
Would be interested in using GPIO for turning the printer On/off after finishing print. Using a relay-Switch would do the job!
Maybe as a Plugin?
Would like to contribute there but i am a relative noob on linux esp RPI...

**Comment by foosel** [comment]
Basic functionality is already possible through the system menu since a long time.

More sophisticated utilization of GPIO related things is possible through plugins, as demonstrated by a number of plugins that are already on the repository.

OctoPrint is cross platform and hence something as platform specific as GPIO will always be something that has to be done through a plugin, and on top of things something like "general control of GPIO" is too unspecific even as a plugin request. This ticket now contains various "it would be need to do X via GPIO" requests, and all of them are things that be easily doable via a plugin (maybe even existing ones).

Since none of those are action points for OctoPrint itself though and either too generalized or way too personal usecase specific to be suitable as a plugin request, I'll close this now.

**Comment by bwaslo** [comment]
One hardware function that the systems menu can't help (unless you can get to it) is shutdown of the Raspberry Pi system.  Pi has an issue that its SD card can get corrupted if powered down while Pi is writing to it, so I shut down the Octopi before removing power.    Which means I have to get to a computer or remember to bring my phone before I can turn off the Pi and its printer.  It would be great if one of the GPIO pins (and another for an indicator) could be used to trigger a Pi shutdown right from the Pi board itself.

**Comment by Duckle29** [comment]
I beleive this would be a feature best implemented in octopi, not octoprint, as there's a dtoverlay for this
https://www.stderr.nl/Blog/Hardware/RaspberryPi/PowerButton.html

**Comment by bwaslo** [comment]
Duckle29, thanks for that link!  (I also posted a request at the Octopi github, but not sure whether that is still being updated).  I'll look into what the link describes, it seems it might be just what I wanted, saving the need for deep code changes.

**Comment by Duckle29** [comment]
octopi is the recommended installation method on rpis, it's updated occasionally. Usually on version increases, though sometimes on patch increases too. once installed, octoprint can usually update itself just fine through the web interface :)

**Comment by bwaslo** [comment]
Mikkel, I just implemented the switch as described on that link and added
the line to the text file.  Seems to be working as described.   That was a
lot easier than I expected!  Thanks.
