### ISSUE TITLE
Fix G-Code Viewer permissions

### ISSUE THREAD

**Issue by hexane360** [foosel/OctoPrint#2779]
#### What were you doing?

This is halfway between a feature request and a bug report. There are a lot of buggy symptoms, but I think the solution involves new features.

When using the `GCODE_VIEWER` permission without `FILES_DOWNLOAD`, all sorts of errors occur.

#### What did you expect to happen?

Either `GCODE_VIEWER` should forcibly enable `FILES_DOWNLOAD`, or `GCODE_VIEWER` should be able to function without `FILES_DOWNLOAD` (possibly by having a special path to download the currently loaded file). This would allow `GCODE_VIEWER` to show print progress for users that don't have full file access.

I realize that the permissions manager makes specific mention that `GCODE_VIEWER` includes `FILES_DOWNLOAD`, but there's a legitimate reason for wanting to use one without the other, and the current setup silently fails instead of providing clear feedback.

#### What happened instead?

Several related errors occur. Usually, it just involves a broken G-Code Viewer tab. If a file is loaded and then `FILES_DOWNLOAD` is revoked, reloading the G-Code Viewer tab results in a 500 error:
```
2018-08-03 16:57:12,579 - tornado.application - ERROR - Uncaught exception GET /downloads/files/local/test.gcode (127.0.0.1)
Traceback (most recent call last):
  File "~/OctoPrint/venv/local/lib/python2.7/site-packages/tornado/web.py", line 1510, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "~/OctoPrint/src/octoprint/server/util/tornado.py", line 918, in get
    self._access_validation(self.request)
  File "~/OctoPrint/src/octoprint/server/util/tornado.py", line 1150, in f
    validator(flask.request, permission)
  File "~/OctoPrint/src/octoprint/server/util/flask.py", line 1066, in permission_validator
    user = _get_flask_user_from_request(request)
  File "~/OctoPrint/src/octoprint/server/util/flask.py", line 1093, in _get_flask_user_from_request
    user = octoprint.server.util.get_user_for_apikey(apikey)
  File "~/OctoPrint/src/octoprint/server/util/__init__.py", line 187, in get_user_for_apikey
    return octoprint.server.userManager.find_user(session=flask_login.current_user.session)
  File "~/OctoPrint/venv/local/lib/python2.7/site-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AnonymousUser' object has no attribute 'session'
2018-08-03 16:57:12,581 - tornado.access - ERROR - 500 GET /downloads/files/local/test.gcode (127.0.0.1) 3.56ms
```

#### Did the same happen when running OctoPrint in safe mode?
I haven't tested this, because I'm running a fresh installation

#### Version of OctoPrint
devel HEAD (44fcd4e305559a46ce97dd8d3992e65499d450b9)

#### Operating System running OctoPrint
Ubuntu MATE 18.04

#### Printer model & used firmware incl. version
Virtual Printer

#### Browser and version of browser, operating system running browser
Firefox Nightly 63.0a1

#### Link to contents of Javascript console in the browser
There isn't anything out of the ordinary in any of the above.

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by foosel** [comment]
That took a while to finally get around to.

I'm note sure I have correctly reproduced this issue. The only problem I could reproduce was related to anonymous/guest users with only the `GCODE_VIEWER` permission, because they weren't properly returned on the tornado API endpoints (which the needed file download is a part of). I've fixed that now in the above commit and it's working flawlessly over here. Removing the `FILES_DOWNLOAD` permission from logged in users didn't produce any kind of errors at all.

It would be great if you could check if you can still somehow reproduce it, I couldn't based on the steps outlined by you.

> or `GCODE_VIEWER` should be able to function without `FILES_DOWNLOAD` (possibly by having a special path to download the currently loaded file).

That wouldn't make sense. If the browser can download the file to display it in the viewer, the user can download the file. There's no way to prevent the user from accessing what their browser (session) can access. In which case it only makes sense to imply the corresponding permission.
