### ISSUE TITLE
Path to tracking plugin given on tracking.octoprint.org not present

### ISSUE THREAD

**Issue by lf-** [foosel/OctoPrint#2797]
At the bottom of tracking.octoprint.org, the page says that the tracking/telemetry plugin source code is at src/octoprint/plugins/tracking. That path doesn't seem to exist. At the same time, I remember having agreed to use the system, so the code should probably be present in a recent ish version. 

I wanted to file this bug on the repo for the site but issues were disabled. 

[x] I have read the FAQ.

**Comment by foosel** [comment]
Look into the [sources of the `maintenance` branch](https://github.com/foosel/OctoPrint/tree/maintenance/src/octoprint/plugins/backup) - as stated on the page the plugin is bundled starting with version **1.3.10**, the `master` branch always contains the stable release version and hence **1.3.9**.

The version you are running is probably a manually checked out version of either `maintenance` (1.3.10.dev) or `devel` (1.4.0.dev) - sadly it's impossible to tell though since you didn't state your version ;)
