### ISSUE TITLE
Request: automatic shutdown after print complete

### ISSUE THREAD

**Issue by fire-buster76** [foosel/OctoPrint#283]
is it possible to implement a checkbox to shutdown the pi after the print ist complete?

**Comment by nixomose** [comment]
So this is perfect, almost. I find that the checkbox is off the screen and I often forget to select it. Is there a way for "shutdown after print" to happen by default?
I'm not a great jquery guy so I wasn't able to follow it all. I found a place in the init.py where it defaults the shutdown flag to false, so I set it to true, but I'm not sure that's enough. thoughts? suggestions? thanks.

**Comment by foosel** [comment]
@nixomose you are talking about [this plugin](http://plugins.octoprint.org/plugins/automaticshutdown/) I guess?

Such a question would be better suited in the issue tracker of that plugin. Personally I'm not completely sold on having something like this default to `true` and having OctoPrint start a shutdown countdown I have to click away after every single small print ;) In any case, the location in ``__init__.py`` you found is the correct place.

You might instead like to look into just [reordering your sidebar via your `config.yaml`](http://docs.octoprint.org/en/master/configuration/config_yaml.html#appearance) though, so that the plugin is e.g. right after the state view. For that the following YAML snippet should work:

``` yaml
appearance:
  components:
    order:
      sidebar:
      - connection
      - state
      - plugin_automaticshutdown
```

or copy-paste this into the YAML Patcher plugin for the same effect (note to self: find out why the patcher doesn't accept the YAML snippet on its own):

    [["set", "appearance.components.order.sidebar", ["connection", "state", "plugin_automaticshutdown"]]]

Should look like this in the patcher:

![image](https://cloud.githubusercontent.com/assets/83657/12744216/472c8856-c993-11e5-8672-b5cc140044bc.png)

and the result should look like this:

![image](https://cloud.githubusercontent.com/assets/83657/12744228/5326ff06-c993-11e5-8216-4ea389a00a16.png)

Also, I forgot to close this request after the plugin was published, correcting that now ;) Doesn't mean comments are closed, just that the request is resolved.

**Comment by nixomose** [comment]
Thanks for the information. I wasn't suggesting changing the plugin to default to on, but I just wanted to be able to do that for me, so I changed mine and now I've got what I'm looking for. You made a funny comment about small little prints. All my prints take hours, so I just leave it running overnight and want it to shut the printer off when it's done so it's not running all night doing nothing.
Thanks again.

**Comment by totalitarian** [comment]
I'm confused how this plugin works. If I tick the box to auto shutdown, then reload the main page, the tick gets removed and I get no automatic shutdown. Is this how it's supposed to work?

**Comment by gnosis953** [comment]
I also do not understand how this plug in works.  The checkbox flashes automatically. Sometimes it is checked sometimes not.

**Comment by nixomose** [comment]
I sounds like it works "incorrectly." :-)
I dunno ,I never had that problem, it usually starts off life unchecked until you set it. Never saw it blink before.

**Comment by gnosis953** [comment]
I think i t has something to do with the "Remember the value of "Shutdown after Print finishes"" in the setting. I unchecked this and it does not flash anymore.
Maybe it will work correctly now. I am trying....

**Comment by foosel** [comment]
I suggest you take all this discussion to the plugin's tracker.

**Comment by totalitarian** [comment]
Gina, we did but it was abandoned.

**Comment by foosel** [comment]
And it is no longer (hasn't been for a couple of weeks in fact) or I
wouldn't have suggested that.

>

**Comment by totalitarian** [comment]
Apologies Gina.

**Comment by foosel** [comment]
As a follow-up to that, there also had been a new release, @kantlivelong has been a busy bee and pounded that plugin back into shape so if you haven't yet I suggest you update (through uninstall & reinstall, old version of plugin couldn't yet update automatically).

**Comment by totalitarian** [comment]
Thanks again. The fact there wasn't an update prompt made me assume it was
still abandoned.
