### ISSUE TITLE
[Feature Request] Add support for UltiGCode

### ISSUE THREAD

**Issue by nicolinux** [foosel/OctoPrint#302]
With the new Ultimaker 2 Daid has moved some variables from the gcode to the printer firmware. It would be useful if OctoPrint would support it.
https://github.com/Ultimaker/CuraEngine/blob/master/settings.h

**Comment by DailyBombs** [comment]
Any progress on this? =)

**Comment by nicolinux** [comment]
Hey Gina, where can I send hugs and cash to move this up on the list of priorities? :)

**Comment by foosel** [comment]
I thought there was still something daid needed to do? Also from what I gather the only difference is that the generated gcode lacks some things that are usually contained within start and end gcode (I'm still missing a link to a definitive documentation on what fulfilling this request would actually entail)? I

f so, does [this](http://docs.octoprint.org/en/devel/features/gcode_scripts.html) (maybe contained within a custom plugin) already solve this? 

If not, to be blunt, nothing directed at me can move this up, there's just too much more important stuff in the pipeline (like first 1.2.0 and then a lot of catching up on technical debts and further opening up octoprint to plugins) than supporting yet another (and let's be honest not very far spread so far) dialect and this may come as a surprise but I like to do something else from time to time in my free time than using that too for working on OctoPrint, but: I am not the only developer on earth :) this is an open source project, everyone is invited to contribute. @markwal just added support for x3g (Makerbot) printers through a plugin, so if there really is a need I'm sure someone can be found who can tackle and achieve this too (and I'll happily support anyone in adding necessary hooks and extension points needed and not already there from which all users can profit, not only those with a UM2) - it's not that difficult to work with the new plugin system and I've spent a lot of time documenting it so people can start solving exactly such as issues like this one themselves.

So: don't wait for it to happen, jump in yourself, that's the open source spirit! :)

**Comment by Salandora** [comment]
I'm sorryly not owing a UM2 nor I'm aware of what is different in the UltiGcodeFlavor otherwise.
If anyone can give me a full list of differences to the "normal" Reprap-Gcode I could try to make a plugin for that. Of course I would need people to test the plugin because of the missing UM2...

Anyone with an UM2 wants to help here?

**Comment by foosel** [comment]
@Salandora :+1:

**Comment by nicolinux** [comment]
I don't have much time for it either, but I am up for testing.
I have started a thread on the Ultimaker forum - let's see what happens.
http://ultimaker.com/en/community/view/16056-feature-request-please-support-octoprint

**Comment by foosel** [comment]
@nicolinux "I don't have time for that (and I also think it should rather reside in a plugin" is not "This will never happen". @Salandora here is offering help, so why not finally state in this ticket what actually needs to be done (because the links above have since stopped pointing to specific posts too) and verify that per-job start/end gcode as available in devel is not enough? 

You want this to be solved but you are leaving us completely in the dark here what now exactly needs to be done on the host side for this - surely if you want this feature so much it is not too much to take the few minutes to just write it down here? :)

**Comment by nicolinux** [comment]
Sorry for not beeing clear. I assumed too much. I will edit the post and change the text.
The reason why I don't take this matter in my own hands is because I don't always have OctoPrint on my radar. Between the myriad of things that constantly nag for my attention, OctoPrint only pops up once in a while when I remember the good old times™ when it used to work (with another printer). 

Regarding the start/end gcode - I tried to emulate the behaviour myself but I was not able to match it perfectly. There are several posts floating on the forum about it, but nobody managed to do it either. I assume Daid did something in firmware that can not be entierly expressed in gcode.
Other than that, I don't know what needs to be done on the host side.

**Comment by Salandora** [comment]
I checked the Ultimaker2Marlin source a bit, I can now say, without direct access to an UM2 with LCD and the help of @daid it's not possible to get the UltiGCode flavor to work with OctoPrint.
This is most likely because the start/end gcode is hardcoded inside the LCD part of the UM2.
So what is to do well the Start/End code should be converted into something that can be triggered by the GCode.
After that it should be possible to hook into the gcode and check if "UltiGcode" is used or normal gcode.

But as already stated this is nothing I could do without the help of @daid.
Because it's atleast his fork which would need to accept the changes I would have to do.

**Comment by daid** [comment]
I actually recommend against trying to support it. Year wiser, and I now know that UltiCode hasn't been the best decision. And the UM2 supports old style reprap code just fine.

I cut too many corners with UltiCode. And while it was a pretty nice addition at that moment in time. I don't think it will be supported by future printers from Ultimaker. So putting effort in it would mean only for the current generation, not the previous, not the next.

(Note, if you want, I can accept backwards compatible patches to allow access to the UltiGCode features from the USB interface. But I won't put time in it myself, and I think @foosel time can be better spend)

**Comment by foosel** [comment]
@daid thanks. I'd hoped it would boil down to just having to add some custom start/end gcode (which would have been trivial via a plugin), but if there's more happening on the firmware side of things, that needs to be exposed first.

As already stated, I don't have the resources myself to look into this (and judging from what you wrote above there would indeed be things that would make more sense to spend them on), but if @Salandora still wants to give it a shot I won't stop him.

That being said: in one sentence, what does ultigcode even do?

**Comment by Salandora** [comment]
My guess at the moment is to stop putting effort in it, I do not have a UM2 to test things, for me it is much to expensive so I'm sure I will not get one in the near feature, well ok maybe if someone wants to spend me one but I believe this will not happen :-), @daid said it's very unlikely that UltiGcode will be supported further on. 
So it is just a waste of time atm.
I consider this for me as unsupportable.

Oh and thanks for the statement @daid. 
That helped a lot in deciding how to go on with this. At least for me.

One more thing @daid maybe it is helpful for others if you would help them convert the start and end code into something reusable, because most of them seem to be very happy with the code.

**Comment by foosel** [comment]
In that case I'll close this as won't implement since if the author of the feature itself says it's doomed, there indeed is not much point in keeping it open. If Ultimaker decides to continue using UltiGcode this can be reevaluated. From what I gather OP can happily work with UM2 if people slice to regular gcode flavor, so there exists a viable workaround that doesn't involve hacking firmware.

**Comment by daid** [comment]
@foosel Just for reference. UltiGCode does the following:

* Start of the GCode file has meta data on filament length used and print time estimate from Cura (which is quite accurate)
* Print temperature, bed temperature, filament diameter, retraction amount&speed and fan speed max are set by the machine from a material profile in the machine.
* Start/end of print is handled by the printer, not in the gcode.

**Comment by markwal** [comment]
@nicolinux by the way, if what you're after is gcode scaling based on filament diameter or extrusion rates, we could do that in a plugin.  There are at least two different ways of going about this.  One would be to always generate the gcode at a nominal filament width and then we could have material profile manager in octoprint that scaled the extrusion axis based on actual measurements and extrusion factor.  The other way would be to use the volumetric extrusion features with material selection at print start.

We could also do a feature that did conditional start gcode based on a selected material profile for the stuff daid mentioned and override them in the gcode (plugins can filter the gcode). Of course, this isn't a request to foosel for OctoPrint so much as to the community of plugin writers to make such a plugin.  Might be fun actually.  The one yucky one (IMHO) is the retraction amount/speed. Overriding the slicers intent on that one might be kind of tricky to do reliably.

**Comment by nicolinux** [comment]
@markwal Good idea - thanks!
What I am really after is fan speed and temperature because these are about the only constants that change (for me) between prints. I wrote it down on this forum post on the Ultimaker forum:
http://ultimaker.com/en/community/view/16078-start-end-gcode-for-um2

Of course a proper material profile manager in OctoPrint would be cool...

**Comment by daid** [comment]
@markwal @nicolinux Cura support an experimental "RepRap volumatic" slicing, which uses G10 and G11 for retraction (same as in UltiGCode) and generates E values in mm^3. But does not depend on the machine for start/end code.

**Comment by markwal** [comment]
I have an Ultimaker 2 now and I finally understand what daid was saying earlier.  ;FLAVOR UltiGCode is only noticed by the firmware when it loads a file from the SD card.  There's just no way to send it over the USB cable even if you have an UltiGCode file and even if we didn't strip comments.  So now, I'll try the Reprap volumetric mode you mentioned.
