### ISSUE TITLE
Temperature readings for a Cyclops (nonmix) on Tronxy Chitu Firmware

### ISSUE THREAD

**Issue by Stady234** [foosel/OctoPrint#3048]
#### What were you doing?
printing as normal

#### What did you expect to happen?
Tool-head temp to be tracked correctly

#### What happened instead?
The initial "preheat"/ or start temp shows the Nozzle receiving the correct TARGET temp.  About 2-5 seconds later, it either shows as "off" or the same as bed temp.

#### Did the same happen when running OctoPrint in safe mode?

yes

#### Operating System running OctoPrint

OctoPrint 1.3.10 running on OctoPi 0.15.1

#### Printer model & used firmware incl. version

TronXY X5ST-2E -- Custom Chitu (from Tronxy)

#### Browser and version of browser, operating system running browser

Chrome (current)

#### Link to octoprint.log

https://gist.github.com/Stady234/2ee9f11695926d70b22321289504ab1e

#### Link to contents of terminal tab or serial.log

https://gist.github.com/Stady234/65d359c6974bb9dc868d5c3c0ecabefe

#### Screenshot(s)/video(s) showing the problem:

![image](https://user-images.githubusercontent.com/32916064/52745082-dc143f80-2fa3-11e9-873a-2043a16a3568.png)

I have read the FAQ.

**Comment by foosel** [comment]
OctoPrint will always take your firmware's reported temperature as the ultimate truth. During heatup, if your firmware doesn't report back the target temperature it will report back the last temperature it *set* on the printer. Once the first full temperature report is received from your firmware, OctoPrint will take all temperatures available in that and take them at face value. Additionally, if your firmware is reporting values for both `T` and `T<current extruder>`, OctoPrint will take the values reported for `T<current extruder>` which usually should match `T`:

https://github.com/foosel/OctoPrint/blob/8ce2290d63ed395ef1b1caa74537a517eac9efb2/src/octoprint/util/comm.py#L4197-L4283

Now let's take a look at what your firmware is reporting:

```
Send: N472351 M105*17
Recv: ok T:138 /215 B:57 /60 T0:138 /60 T1:138 /0 @:128 B@:128
```

`T` is reported with actual 138°C, target 215°C. `T0` however is reported with actual 138°C, target 60. Your firmware's temperature reporting is broken and needs to be fixed by the vendor.

In the meantime, if coding is an option for you you could work around this nonsense with [a plugin that fixes the temperature report lines as they are received](http://docs.octoprint.org/en/master/plugins/hooks.html#octoprint-comm-protocol-gcode-received).
