### ISSUE TITLE
AttributeError: 'module' object has no attribute 'main'

### ISSUE THREAD

**Issue by araujotassia** [foosel/OctoPrint#3164]
#### What were you doing?

Trying to install from sources in a Debian box following the instructions at https://community.octoprint.org/t/setting-up-octoprint-on-a-raspberry-pi-running-raspbian/2337

"virtualenv venv" fails.

#### What did you expect to happen?

A clean installation.

#### What happened instead?

```
pi@raspberrypi:~/OctoPrint $ virtualenv venv
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/pi/OctoPrint/venv/bin/python2
Not overwriting existing python script /home/pi/OctoPrint/venv/bin/python (you must use /home/pi/OctoPrint/venv/bin/python2)
Installing setuptools, pkg_resources, pip, wheel...
  Complete output from command /home/pi/OctoPrint/venv/bin/python2 - setuptools pkg_resources pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 24, in <module>
AttributeError: 'module' object has no attribute 'main'
----------------------------------------
...Installing setuptools, pkg_resources, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2375, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 724, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 992, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 922, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 817, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/pi/OctoPrint/venv/bin/python2 - setuptools pkg_resources pip wheel failed with error code 1
```

#### Version of OctoPrint

lastest from github.

#### Operating System running OctoPrint

Debian Stretch.

I have read the FAQ.

**Comment by foosel** [comment]
If creating a virtual environment with `virtualenv` already fails, that is a bug in the version of `virtualenv` that's shipped with Debian stretch or some issue with your installation.

`virtualenv` is a standard Python tool not under my control, and I fear you'll have to report that issue somewhere else. I'm not sure if the bug tracker for virtualenv or Debian's bug tracker is the right place here though.

Side note: This looks like your `virtualenv` is trying to do stuff with Python 3 library files even though you have called `python2`. So maybe that's the issue here. OctoPrint 1.3.x (so the current stable versions) only support Python 2.
