### ISSUE TITLE
[Request]: Allow specific named files to be uploaded to sdcard for easy firmware upgrade. 

### ISSUE THREAD

**Issue by eikeime** [foosel/OctoPrint#3215]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**

Current filemanager of octoprint only allow .gcode,.gco,.g to be uploaded, please add an option in the settings that let users set a specific file name like "firmware.bin" to be allowed to upload to sdcard for easy firmware upgrade. this is a much simpler way to upgrade firmware than the firmware updater plugins. And for safety octoprint can request a password when that file name was detected.

**Describe alternatives you've considered**

**Additional context**

**Comment by foosel** [comment]
That is already possible through plugins, either through the expansion of the [file extension tree](https://docs.octoprint.org/en/devel/plugins/hooks.html#octoprint-filemanager-extension-tree) or - probably better - by directly utilizing the communication layer to upload a specific file. If the firmware is able to handle file uploads via serial in a manner that doesn't destroy binary data is a whole different challenge however.

See also #1652 of which this is a duplicate, which is why I'm closing this.
