### ISSUE TITLE
OctoPrint continues to send M27 even after SD card print completes successfully

### ISSUE THREAD

**Issue by kazibole** [foosel/OctoPrint#3258]
#### What were you doing?

SD card print starts and completes successfully, however OctoPrint continues to send M27 every "SD status interval (polling)" (default is 1 second).

```
2019-08-19 21:24:57,294 - Send: M27
2019-08-19 21:24:57,303 - Recv: Not SD printing
2019-08-19 21:24:57,306 - Recv: ok
2019-08-19 21:24:58,295 - Send: M27
2019-08-19 21:24:58,305 - Recv: Not SD printing
2019-08-19 21:24:58,307 - Recv: ok
2019-08-19 21:24:59,297 - Send: M27
2019-08-19 21:24:59,305 - Recv: Not SD printing
2019-08-19 21:24:59,308 - Recv: ok
2019-08-19 21:25:00,298 - Send: M27
2019-08-19 21:25:00,308 - Recv: Not SD printing
2019-08-19 21:25:00,312 - Recv: ok
2019-08-19 21:25:01,300 - Send: M27
2019-08-19 21:25:01,326 - Recv: Not SD printing
2019-08-19 21:25:01,331 - Recv: ok
```

I am still able to start the next SD card print without any issues.

#### What did you expect to happen?

The M27 polling commands to stop.

#### What happened instead?

The M27 polling commands continue indefinitely.

#### Did the same happen when running OctoPrint in safe mode?

Yes

#### Version of OctoPrint

OctoPrint 1.3.11

#### Operating System running OctoPrint

OctoPi 0.15.1

#### Printer model & used firmware incl. version

Prusa MK3 firmware 3.8.0-RC1 (occurs on 3.8.0-RC2 as well)

#### Link to octoprint.log

https://gist.githubusercontent.com/kazibole/fd5230ca6468dc2042e6df470edc2114/raw/6f9e0fcd694048fff8f42be9e7f4d499898f76a3/octoprint.log

#### Link to contents of terminal tab or serial.log

https://gist.githubusercontent.com/kazibole/fd5230ca6468dc2042e6df470edc2114/raw/6f9e0fcd694048fff8f42be9e7f4d499898f76a3/serial.log

I have read the FAQ.

**Comment by foosel** [comment]
That's expected and correct behaviour.

The way firmwares report on SD card "activity" means I only get a message when an SD file is selected for printing, not when printing actually starts, unless I actively query status via `M27` (or the firmware autoreports). Meaning, if you select an SD file and then start the print through the controller, this will only get picked up as a print start if the SD status is monitored.

Which is why as long as an SD file is selected for printing, OctoPrint will monitor the SD status through `M27`. Once you select a different file not on the printer's SD, the polling should stop.

If I could rely on all of the thousands of firmware variants out there sending proper action commands on print starts/stops and so on and also had a bit more verbose SD responses, that would not be necessary, but sadly, as things are, it is.
