### ISSUE TITLE
[Request] Don't send tracking information if not printing

### ISSUE THREAD

**Issue by WilkoV** [foosel/OctoPrint#3291]
OctoPrint sends 200 - 300 tracking information per day and no print is running. I don't think this is necessary. 

I know it's not a real problem but the value of this data is questionable for me. Only send data if prints are running.

**Comment by foosel** [comment]
OctoPrint sends this data (which btw is fully documented [here](http://tracking.octoprint.org/)) since not only prints are relevant to figure out deployed instances, versions, plugin data, and so on.

If you do not want this data to be tracked, please disable the tracking plugin [as instructed](http://tracking.octoprint.org/).

I can assure you that all of the data that is getting tracked has value and is getting tracked for a specific reason that is relevant to development and release rollout monitoring.
