### ISSUE TITLE
Extrude only move too long (-4070.119mm vs 100.000mm) - 1.3.12rc3

### ISSUE THREAD

**Issue by louispires** [foosel/OctoPrint#3303]
#### What were you doing?

1. Started a Print (Bed and Hotend was Pre-Heated) - [File (GCODE)](https://filebrowser.louispires.com/share/dU6Lv0oj)
2. Opened [Canceled Object Tab](https://github.com/paukstelis/OctoPrint-Cancelobject)
3. Canceled 1 of the 2 parts: ![image](https://user-images.githubusercontent.com/8841644/66648780-b15eb180-ec2c-11e9-858e-44b89f3a06eb.png)
4. Print went smoothly until about Z14.4
5. Error inside [octoprint.log](https://gist.github.com/louispires/a4dc0032364f2e52d3d4c36eda0e533d):  **WARNING - Received an error from the printer's firmware: Extrude only move too long (-4070.219mm vs 100.000mm)**

#### What did you expect to happen?
I expected the print to continue and complete as it was for the first 14mm of the print.

#### What happened instead?
The error occurred which canceled the entire print.

#### Did the same happen when running OctoPrint in safe mode?
I have not had a chance to retry the print.

#### Version of OctoPrint
OctoPrint (1.3.12rc3)
Cancel Objects (0.3.3)

#### Operating System running OctoPrint
OctoPi (0.17.0)

#### Printer model & used firmware incl. version
Ender 3 running Klipper v0.7.0-796-gf21f66a

#### Browser and version of browser, operating system running browser
Chrome and Windows 10

#### Link to octoprint.log
[octoprint.log](https://gist.github.com/louispires/a4dc0032364f2e52d3d4c36eda0e533d)

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by foosel** [comment]
I fear that is nothing that is new in 1.3.12rc3 or a bug in OctoPrint, but it rather looks like your firmware got a command there it didn't like (in place extrusion) which got generated by the CancelObject plugin due to you cancelling a part of the print. I suggest reporting this on the plugin's issue tracker, it could be that it's generating wrong command here, though I cannot see that in the log, you'd need to create a `serial.log` for that. As far as I understand the firmware error here, the cancellation causes a extrusion-in-the-same-spot that is way way past a threshold value and that make the firmware trigger an error. OctoPrint has to assume this error means something horrible has happened (it treats all errors it hasn't explicit parser routines for as such, and this is the first time I have ever seen this error and I frankly don't even know what state the firmware is in after) and thus cancels the print.
