### ISSUE TITLE
Octoprint pauses SD card prints on my MK3S + MMU2S

### ISSUE THREAD

**Issue by wpegden** [foosel/OctoPrint#3440]
I am printing on an MK3S + MMU2S.  It is set up correctly with 5 tools, single extruder.

I can print through octoprint and have also successfully monitered SD card prints.

But now octoprint is pausing all SD card prints right after they start

It sends an M108 and then an M27 command to the printer.

like this:
Send: M108
Recv: Unknown M code: M108
Recv: ok
Send: M25

the M25 command pauses the print.

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by foosel** [comment]
Thank you for reporting this!

Sadly your report lacks some of the information that is needed in order to look into this issue:

  * steps to reproduce
  * whether you have been able to reproduce this issue in safe mode too
  * your [exact version of OctoPrint](https://discourse.octoprint.org/t/how-can-i-find-out-the-version-of-octoprint-or-octopi-i-am-running/204/1)
  * your [exact version of OctoPi](https://discourse.octoprint.org/t/how-can-i-find-out-the-version-of-octoprint-or-octopi-i-am-running/204/1)
  * the operating system running OctoPrint (name *and* version please)
  * the browser with which you are seeing this (underlying OS and full version please)
  * unmodified full length [`octoprint.log`](https://discourse.octoprint.org/t/where-can-i-find-octoprints-and-octopis-log-files/299/1)
  * contents of the terminal tab, or even better a [`serial.log` (please enable that first though, it's not being written by default)](https://discourse.octoprint.org/t/where-can-i-find-octoprints-and-octopis-log-files/299/1)
  * the contents of [your JS error console](https://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers)
  * screenshots or maybe a video showing the problem

(If you need help with locating this stuff, please take a look [into the Contribution Guidelines](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md#what-should-i-include-in-a-bug-report) which explains everything - and if anything is still unclear then just ask)

Could you please provide that so this issue can be analyzed and ideally reproduced and fixed? Thank you!

**Comment by foosel** [comment]
Closing due to lack of response.
