### ISSUE TITLE
Filament runout ends in Emergency stop, or print continues far than stopped

### ISSUE THREAD

**Issue by ochm** [foosel/OctoPrint#3461]
#### What were you doing?
While printing from Octoprint to MK3S and filament is gone, 
the printer goes to M600 - change filament.
After filament change the printer always in wrong way. 
- sometimes print continues, but little bit far than was stopped (some print data are lost?),
- sometimes goes to emergency stop,
- sometimes printer must be restarted (on display are messy characters).
I tested it many times on two printers with the same random reslults.

When the printer goes to emergency stop (after filament is changed and we want to continue in print) in the terminal i see:
Send: G1 Z0.200
Recv: fsensor_checkpoint_print
Recv: Resend: -2
Printer requested line 2 but no sufficient history is available, can't resend
Changing monitoring state from "Printing" to "Error: Printer requested line 2 but no sufficient history is available, can't resend"
Send: M112
Send: N1 M112*32
Send: N2 M104 T0 S0*35
Send: N3 M140 S0*102
Changing monitoring state from "Error: Printer requested line 2 but no sufficient history is available, can't resend" to "Offline (Error: Printer requested line 2 but no sufficient history is available, can't resend)"
Connection closed, closing down monitor
Closing down send loop

#### What did you expect to happen?
After filament change to continue where the print stopped.
When in gcode is M600, or the filament change action is called from printer's menu, 
everything goes well, Octoprint waits with sending data till M600 is finished.
But when fsensor detect filament runout, sometimes it leads to emergency sotp, sometiles M600 starts OK, but the end goes wrong way.
Maybe is problem in printer's Firmware, i don't know, but it seems like the printer is detecting filament runout but doesn't tell the Octoprint to pause print immediately, what leads to print far from point where the filament runout was detected, or it leads to emergency stop....

#### Did the same happen when running OctoPrint in safe mode?
Yes, it doesn't mater.

#### Version of OctoPrint
OctoPrint version : 1.3.12

#### Operating System running OctoPrint
OctoPi version    : 0.17.0

#### Printer model & used firmware incl. version
MK3S 3.8.1, 3.9.0RC1

I have read the FAQ.

**Comment by foosel** [comment]
This is a problem with the printer's firmware, it's requesting a negative line number which doesn't even make remotely sense, which is why OctoPrint assumes something to have gone terribly wrong and kills the print and printer with M112 in order to not risk heaters staying on. The reason needs to fixed on the firmware side.

The correct firmware behaviour would be to simply utilize the busy protocol to tell OctoPrint it's waiting for the user to swap filament and/or to send an action command to pause the print. 

PS: next time please share *all* requested information, not just log excerpts and selected data points.
