### ISSUE TITLE
SD card Print Time Left estimation inaccurate

### ISSUE THREAD

**Issue by NightSkySK** [foosel/OctoPrint#3495]
#### What were you doing?

Print file from SD card, which was started on printer it self using Prusa MK3S +MMU2S

#### What did you expect to happen?
Estimated Print Time Left to be in line with reported by the printer by terminal.

#### What happened instead?
The estimate Print Time Left is over 10 times longer than calculated by the printer.
But on the terminal printer is reporting estimated time to finish, which is not taken under consideration to calculate Print Time Left. 

#### Did the same happen when running OctoPrint in safe mode?
Didn't check.

#### Version of OctoPrint
OctoPrint 1.4.0 

#### Operating System running OctoPrint
running on OctoPi 0.17.0

#### Printer model & used firmware incl. version
Orginal Prusa i3 MK3S + MMU2S Firmware 3.8.1 (1.0.6)

#### Link to contents of terminal tab or serial.log
[Terminal](https://pastebin.com/iJa6truH)

#### Screenshot(s)/video(s) showing the problem:
![image](https://user-images.githubusercontent.com/52137446/77737564-8f0bf500-700e-11ea-913a-3886bc0348f2.png)

I have read the FAQ.

**Comment by foosel** [comment]
> But on the terminal printer is reporting estimated time to finish, which is not taken under consideration to calculate Print Time Left.

Because it is a Prusa specific firmware modification and nothing OctoPrint can rely on to receive from any other printer out there. THe common denominator OctoPrint has is bytes printed vs total bytes against time needed. That's what it uses for SD prints since it doesn't have *any* other data and depending on the structure of your GCODE, yes, that can make it VERY inaccurate. That's not something that can be changed. 

Someone could write a custom plugin to evaluate these special firmware messages, but this is not something I'm going to add to core because then I'll drown in printer specifics and that simply is not maintainable.
