### ISSUE TITLE
Update printer firmware via Pi?

### ISSUE THREAD

**Issue by nhfoley** [foosel/OctoPrint#351]
This would be sweet feature.

**Comment by ignaworn** [comment]
For those who want to compile/upload from the raspberrypi. I managed to do it like this

Install the packages, arduino libraries, make (doublecheck) and pyserial (should be installed if already running OctoPrint). And clone the sources, in my case I tested Repetier Firmware devel branch.
I did not use arduino-mk from Raspbian repo because was outdated and didn't compile.

>sudo apt-get install -y arduino make pyserial
cd ~
git clone https://github.com/sudar/Arduino-Makefile.git
git clone https://github.com/repetier/Repetier-Firmware.git
cd Repetier-Firmware
git checkout work092

Create the makefile, if you are using a different board try ```make show_boards``` 
>cd ~/Repetier-Firmware/src/ArduinoAVR/Repetier
cat > Makefile <<EOT
BOARD_TAG    = mega2560
ARDUINO_PORT = /dev/ttyACM*
include ~/Arduino-Makefile/Arduino.mk
EOT

Then edit/replace configurations.h and then verify ```make``` or compile/upload ```make upload```
Just remember to release serial communication from Octoprint. (maybe ```sudo service octoprint stop``` before and ```sudo service octoprint start``` after flashing.

**Comment by jneilliii** [comment]
Isn't this resolved by https://plugins.octoprint.org/plugins/firmwareupdater/

**Comment by gege2b** [comment]
yeah, at least partially (the plugin does not support every single board available right now out of the box), 

But as long as the firmware can be uploaded with avrdude on the board, it's only a matter of adding one/two lines in the plugin HTML template (that's what I did for my old sanguinololu board and it works well)

Compilation of the firmware still needs to be done separetly

@foosel I think this can be closed

**Comment by foosel** [comment]
Ah, good point!
