### ISSUE TITLE
Live Feedrate/Flowrate Control: feature request

### ISSUE THREAD

**Issue by AJdoodler** [foosel/OctoPrint#362]
It would be nice to add a control feature that would allow the user to throttle up/down the feedrate and flowrate during a print.

**Comment by foosel** [comment]
Implemented in `devel`

**Comment by maukcc** [comment]
I love the sliders, and so I want more :)
Slider for fans, lights, temps,...
Can we make it so that we(users) can do this in the config.yaml file, for whatever we need.
Also it took me a while to understand that I had to click the button to implement the change. That is 1 click too many.

**Comment by foosel** [comment]
> Can we make it so that we(users) can do this in the config.yaml file, for whatever we need.

... => http://docs.octoprint.org/en/devel/features/custom_controls.html

> Also it took me a while to understand that I had to click the button to implement the change. That is 1 click too many.

For some it's one click too many, others want the added safety cushion. From a technical point of view, each modification necessitates sending a command to the printer. During printing that means adding control overhead to the line. If you have to click the button, I only have to send one command instead of one per change. That's better for performance.

> Also if you log out and back in, the sliders are back to 100%, is there any way of getting the actual info back from the machine.

No, there isn't.

**Comment by gitsly** [comment]
Hi, I would like to be able to adjust the maximum percentage of speed up (in config.yaml etc.)
Is this possible atm. didn't find anything 150ish in my entire config.
The reason being that I have a kossel optimized for fast printing which prints nicely at 90mm/s.
However I'm trying to minimize wear on the printer so I always slice with 30mm/s feedrate and only adjust the slider (repetier used before) when I'm really in a hurry... I would like my slider to go from 20%->300%

**Comment by MarcusWolschon** [comment]
There's no way to get the current flow rate (so as to not display % but mm/s) is there?

I'm also interested because I'm doing a filament sensor and if the filament should not move at the moment (e.g. machine heating or cooling or waiting for a minimum-layer-time) then it should not cause an alarm that the sensor doesn't detect any filament movement.

**Comment by markwal** [comment]
@MarcusWolschon no.  Even watching the commands go by on send won't be very accurate for this due to two factors: First, firmware's have a command buffer, so the speed of the currently executing command is a command buffer full of commands earlier than the current command being sent.  Also, the current actual speed differs from the commanded speed due to firmware calculations like maximum speed, acceleration and jerk.

There are sensors like this out there, but they guess on reasonable feed over time (mostly upper limit on stationary filament) like the Tunell monitor: https://www.toybuilderlabs.com/products/tunell-3d-printer-filament-monitor  Some firmware/motherboard combos have a mechanism for a pin pulled low (or high) causing a pause (sailfish calls it p-stop) that this integrates with.  You could also do that in an OctoPrint plugin and gpio on a Pi.

However, to be precise on measuring the difference between expected filament consumption and actual feed, you'd need a more cooperative firmware that can output in some way the current expect consumption.  If you did do this, it'd be pretty cool because you could also adjust for material friction and diameter differences and other feed differences automatically.

**Comment by beemeeup** [comment]
Is it possible to have help Texts while floatining over the Button Element???

I am always confused about the difference between Flo and Feerate....
