### ISSUE TITLE
Position memory when Paused

### ISSUE THREAD

**Issue by connerk** [foosel/OctoPrint#366]
Similarly mentioned in issue #324, memory of the print head's position when a pause is initiated would be useful.

I too pause prints to change filament color. It's great to be able to print name tags and such accurately.

Another function well served by this is re-homing.  If a motor loses steps in a print and it is caught quickly, I am able to Pause, raise Z to clear any curling, Home X and Y, then hit resume to reset the axis to the correct position.
Currently, if I pause in Octoprint, raise Z, move X and Y around, and then resume, it will start extruding plastic at whatever location as if it were still in the position it was paused at.

Thanks Gina et-all for a fantastic product!

**Comment by foosel** [comment]
OctoPrint since 1.3.0 will (try to) persist the last position as reported by `M114` by the firmware (!) on a pause and cancel and provide the result as `pause_position` in the `afterPrintPaused` and `beforePrintResumed` GCODE script context and as `cancel_position` in the `afterPrintCancelled` GCODE script context. It will also provide `last_position` in all GCODE scripts.

See [the docs on that matter](http://docs.octoprint.org/en/master/features/gcode_scripts.html#context), including the warning with regards to limitations in multi extruder setups due to how firmware is currently implemented. An example for a pause routine that takes care of moving the print head out of the way and on resume resetting everything so that coordinates, speed and such match can be found [here](https://gist.github.com/foosel/1c09e269b1c0bb7a471c20eef50c8d3e) and in the release notes of 1.3.0.

Hence closing as implemented.
