### ISSUE TITLE
[feature request] time-lapse on X/Y position

### ISSUE THREAD

**Issue by HamOP** [foosel/OctoPrint#370]
My printer is a mendel type which moves the print plate in X/Y, so the "timelapse on Z chance" doesn't work well for me as the X/Y position is a different one on each Z axis change - the printed object will therefore move around in the time-lapse video, thus creating a very "hectic" type of video. It would be great to be able to specify an X/Y position on which - every time the printer is in this position - a time-lapse picture is recorded. Ideally, this could be combined with an option that this happens only once on each Z position.

I hope this is understandable...

**Comment by foosel** [comment]
Just realized that this actually had a duplicate in #621 

As discussed in length there, while I agree that this would be nice, this is not something that can be done by the host due to [various reasons]().

Something like modifying slicer-per-layer-change-gcode might prove to be more promising here.

So closing since it's pretty much unfeasible as part of OctoPrint in the current firmware/printer-communication environments
