### ISSUE TITLE
[request] Cura settings in the main page (and other minor things)

### ISSUE THREAD

**Issue by fra87** [foosel/OctoPrint#572]
Hi all
I just discovered octoprint, and so, coming from other SWs, i noticed the lack of one really useful function: you can't edit cura settings from the interface.
Then i discovered this: https://github.com/foosel/OctoPrint/issues/477
Ok, it is a good feature, but i think it will be better if, along with this, a box to choose a pre-made config is added to the main window, under the upload button. Just something simple, like the "Select CURA config" combobox in the issue 477.
Another thing it lacks is the management of STL files; once you upload them you can only remove them through the PC, because octoprint only shows gcode files.
Lastly i couldn't find a way to "view" the gcode. It only shows one layer, and i can't view the others (or it shows all of them, i could not understand it). And it lacks the 3d view ;)
These are just a couple of ideas to make this SW better and better.

Thank you for your work!

**Comment by foosel** [comment]
Cura configuration can be chosen in new slicing integration on `devel` branch, STL files can be managed as well, the GCODE viewer only being 2D is intentional since that is also compatible to low speed devices (a 3d viewer would probably crash mobiles), but a 3d viewer could easily be made available and added as a plugin (also `devel`).

PS: Only one request per issue, thanks.
