### ISSUE TITLE
Processor Utilization

### ISSUE THREAD

**Issue by JimZuber** [foosel/OctoPrint#59]
I noticed a couple of things when printing to my PrintrBot Jr with OctoPrint running on a Raspberry Pi...

1)When you load a file into OctoPrint the CPU utilization goes to 100% in the OctoPrint process for a minute or two. It appears the file is being prepped for printing, however the status display above the print button is not updated with the file name so you can't actually use the prepped file. So, in order to print the file, you need to click on the file name, then the open folder icon, then wait for the progress indication to complete, then print. And at the end of the print job, the CPU utilization stays at almost 100% for a minute or two after the job is completed. My guess is that Octoprint is pre-processing the job 3 times, once when you load it, once when you hit the icon to load it, and possibly once when the job is done. At least that is my observation without digging into the code.

2)When running OctoPrint, I noticed that the Raspberry Pi would occasionally crash or I would lose the video feed if I brought a second Octoprint browser window up on another computer. This would happen when I wanted to check on the status of a print job when I was away from the my desktop computer, but had left the browser pointed on the Desktop pointed at OctoPrint. Some measurements revealed that  video feed  sucked up about 5% of the CPU utilization and double if an additional browser was added. A running print job varied between 35% and 75% CPU utilization, and as mentioned above when processing the print job during loading was 90% plus. I found a nice utility called "cpulimit" that I was able to add to the rc.local file to cap the OctoPrint process around 70% CPU utilization. This seemed to create a more stable environment, particularly when multiple browser windows were up. At least so far.

**Comment by jefflikesbagels** [comment]
I'd like to add to the video feed being dropped. I have an RPi B 512MB running the latest master branch of OctoPi along with a usb Microsoft Lifecam VX5000. I'm running the webcam at 640x480 10fps, and mjpg-streamer will crash / lose the feed all too often, even more so when I add more viewers. I have the webcam and a wifi dongle hooked up to a USB hub; I tried it with the webcam directly plugged into the RPi, and no change. I've been keeping an eye out on /var/log/messages and a few other log files, but I simply could not find a line that explains what exactly is happening when the video stream freezes / crashes.

**Comment by foosel** [comment]
Keep in mind that mjpg-streamer is not written nor maintained by me, it's also not part of OctoPrint (although it comes bundled with OctoPi), for OctoPrint it's just a URL embedded in a piece of HTML. So if that one is giving you trouble with your webcam, about the only thing I can do about *that* is suggesting experimenting with the settings or using a different cam.

**Comment by jefflikesbagels** [comment]
My apologies for clogging up this thread. For some reason I forgot that mjpg-streamer was written by someone else. Thanks for your help.

**Comment by foosel** [comment]
No problem. I used to have a LifeCam as well (Studio though, not VX) which gave me very flaky behaviour on my Pi. Locked up randomly and stuff like that. I since switched to a Logitech C270 and haven't looked back (the LifeCam is now my regular webcam for video conferences instead).

I also just realized, skimming over this ticket, that the current state of both the master and the devel branch is so significantly different than the one from back then and that most if not all observed issues were addressed since then one way or another, that it doesn't make much sense to keep this here open.

What has changed since then (at least concerning this ticket ;)):
- Upload streaming (mitigating the memory consumption when uploading large files) => in `devel`
- Download streaming (mitigating the memory consumption when downloading large files) => in `master` and `devel`
- GCODE visualizer gets disabled by default for files larger than X (X being different for desktop and mobile browsers), can be manually activated by the user with one click => in `devel`

**Comment by OutsourcedGuru** [comment]
Also (regarding mjpg_streamer), note that there's a v1 and a v2 of the Pi NoIR camera and the first has been discontinued.  The second boasts 8MP so some of you might have the older/newer versions are are comparing apples to oranges with respect to the processing, storage and streaming requirements.  At the 1080p30 video mode that's 1GB of storage every eight minutes and the Robo C2 comes with a 4GB microSD and whose /var/logs could be chock full o' messages unless someone's doing a little maintenance to clean that out.
