### ISSUE TITLE
[Request] Print Percentage in State

### ISSUE THREAD

**Issue by Klikini** [foosel/OctoPrint#703]
![Example](https://cloud.githubusercontent.com/assets/1693960/5603159/d34dff70-933b-11e4-9698-fec0a6f7b5ab.png)
Here's an example with the percentage in the State progress bar during a print, similar to the loading bar in the Gcode viewer tab.

**Comment by foosel** [comment]
I tried that once. The problem is that while it works great once you have some parts of the status bar filled, it is completely unreadable as long as the percentage text doesn't fit the blue bar (white text on light grey background) and trying to fix this (by basically patching the underlying UI framework) is just not worth it.
