### ISSUE TITLE
[Request] Add temperature to 'state' menu

### ISSUE THREAD

**Issue by kev626** [foosel/OctoPrint#757]
Add a spot for temperature to the state of the printer on the sidebar.

**Comment by RemeberMe** [comment]
Yes, please.  I am constantly switching back and forth to view temps.  I don't need a fancy graph, just the present temp would be awesome.

**Comment by foosel** [comment]
Switch to `devel` and use the [Navbar temp plugin](https://github.com/imrahil/OctoPrint-NavbarTemp)

**Comment by RemeberMe** [comment]
Can't.  I'm one of the happy idiots who just used the SD image because I have no idea how to do this manually :) Hal

**Comment by foosel** [comment]
Which is why [it's explained in the FAQ](https://github.com/foosel/OctoPrint/wiki/FAQ#how-can-i-switch-the-branch-of-the-octoprint-installation-on-my-octopi-image) ;)

In any case, while I will not add this to the master branch in the future such stuff will be the job of plugins as can already be seen, so rest assured it's being worked on, only slightly different than expected ;)

**Comment by RemeberMe** [comment]
Thanks Gina!  I've been just a little chicken to try this till I finish off a current project :) Hal
