### ISSUE TITLE
[Request] Event on incoming websocket messages

### ISSUE THREAD

**Issue by punkkeks** [foosel/OctoPrint#812]
It would be awesome to connect to the websocket and send messages over it, instead of creating your own ajax request every time you want to send a message from the browser to the backend. The other way round it works with a little hack:

    self._pluginManager.send_plugin_message("PluginName", message)

why not the other way round? :(

**Comment by foosel** [comment]
Because the websocket is designed as a read only interface, exclusively used throughout the application for pushing status updates to the clients that are of interest to all of them. The whole actual operations are implemented as AJAX calls and plugins inherit that behaviour. Why? Because this way you get a proper HTTP only automatically when implementing your functionality, ready to be used by clients without the need to look into websockets and the sockjs protocol on top of that (and in fact also working when websockets don't). 

It's a conscious decision to prevent having to do everything twice where it's not necessary (state queries providing the same dates that's available on the websocket are implemented additionally on the REST API where necessary, but that's only for a small subset of the whole functionality).
