### ISSUE TITLE
[Request] OctoPrint update from 1.1.1-932-gbe423e4

### ISSUE THREAD

**Issue by manu69x** [foosel/OctoPrint#955]
I tried to update Octoprint 1.2
now I can see "Plugin Manager"
but the reported version is always 1.1
In "Software Update" I have
Installed: 1.1.1-932-gbe423e4
Available: 1.1.2 (stable).
What's wrong ?

**Comment by foosel** [comment]
This is not a request, this is a support question and trying to get around having to file a proper ticket through marking this as a request so the boot well not close it down due to the lack of logs etc is nothing I'll tolerate. Either post to the mailinglist or follow the "How to file a bug report template" to the T.
